use crate::{HeaderAgent, HeaderOptions};

pub fn render_header(opts: &HeaderOptions, agents: &[HeaderAgent]) -> String {
    let guard = include_guard(&opts.library_name);
    let mut out = String::new();
    out.push_str("// Generated by Corvid -- DO NOT EDIT.\n");
    out.push_str("// Phase 22 slices 22-A/22-C.\n");
    out.push_str("//\n");
    out.push_str("// String ABI ownership for this header:\n");
    out.push_str("//   * inbound `const char*` parameters are UTF-8, null-terminated, caller-owned\n");
    out.push_str("//   * outbound `const char*` returns are UTF-8, null-terminated, Corvid-owned\n");
    out.push_str("//   * release returned agent strings with `corvid_free_string(...)`\n");
    out.push_str("//   * release `corvid_call_agent` JSON payloads with `corvid_free_result(...)`\n");
    out.push_str("//   * grounded-return handles are runtime attestations; release them with `corvid_grounded_release(...)`\n\n");
    out.push_str("//   * observation handles are runtime attestations; release them with `corvid_observation_release(...)`\n\n");
    out.push_str(&format!("#ifndef {guard}\n"));
    out.push_str(&format!("#define {guard}\n\n"));
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n\n");
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("#endif\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_TRUST_AUTONOMOUS = 0,\n");
    out.push_str("    CORVID_TRUST_HUMAN_REQUIRED = 1,\n");
    out.push_str("    CORVID_TRUST_SECURITY_REVIEW = 2,\n");
    out.push_str("} CorvidTrustTier;\n\n");

    out.push_str("typedef struct {\n");
    out.push_str("    const char* name;\n");
    out.push_str("    const char* symbol;\n");
    out.push_str("    const char* source_file;\n");
    out.push_str("    uint32_t source_line;\n");
    out.push_str("    uint8_t trust_tier;\n");
    out.push_str("    double cost_bound_usd;\n");
    out.push_str("    uint8_t reversible;\n");
    out.push_str("    uint8_t latency_instant;\n");
    out.push_str("    uint8_t replayable;\n");
    out.push_str("    uint8_t deterministic;\n");
    out.push_str("    uint8_t dangerous;\n");
    out.push_str("    uint8_t pub_extern_c;\n");
    out.push_str("    uint8_t requires_approval;\n");
    out.push_str("    uint32_t grounded_source_count;\n");
    out.push_str("    uint32_t param_count;\n");
    out.push_str("} CorvidAgentHandle;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_CALL_OK = 0,\n");
    out.push_str("    CORVID_CALL_AGENT_NOT_FOUND = 1,\n");
    out.push_str("    CORVID_CALL_BAD_ARGS = 2,\n");
    out.push_str("    CORVID_CALL_UNSUPPORTED_SIG = 3,\n");
    out.push_str("    CORVID_CALL_APPROVAL_REQUIRED = 4,\n");
    out.push_str("    CORVID_CALL_BUDGET_EXCEEDED = 5,\n");
    out.push_str("    CORVID_CALL_RUNTIME_ERROR = 6,\n");
    out.push_str("} CorvidCallStatus;\n\n");

    out.push_str("typedef struct {\n");
    out.push_str("    const char* site_name;\n");
    out.push_str("    const char* predicate_json;\n");
    out.push_str("    const char* args_json;\n");
    out.push_str("    const char* rationale_prompt;\n");
    out.push_str("} CorvidApprovalRequired;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_PREFLIGHT_OK = 0,\n");
    out.push_str("    CORVID_PREFLIGHT_AGENT_NOT_FOUND = 1,\n");
    out.push_str("    CORVID_PREFLIGHT_BAD_ARGS = 2,\n");
    out.push_str("    CORVID_PREFLIGHT_UNSUPPORTED_SIG = 3,\n");
    out.push_str("} CorvidPreFlightStatus;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_FIND_AGENTS_OK = 0,\n");
    out.push_str("    CORVID_FIND_AGENTS_BAD_JSON = 1,\n");
    out.push_str("    CORVID_FIND_AGENTS_UNKNOWN_DIMENSION = 2,\n");
    out.push_str("    CORVID_FIND_AGENTS_OP_MISMATCH = 3,\n");
    out.push_str("} CorvidFindAgentsStatus;\n\n");

    out.push_str("typedef struct {\n");
    out.push_str("    CorvidPreFlightStatus status;\n");
    out.push_str("    double cost_bound_usd;\n");
    out.push_str("    uint8_t requires_approval;\n");
    out.push_str("    const char* effect_row_json;\n");
    out.push_str("    const char* grounded_source_set_json;\n");
    out.push_str("    const char* bad_args_message;\n");
    out.push_str("} CorvidPreFlight;\n\n");

    out.push_str("typedef struct {\n");
    out.push_str("    CorvidFindAgentsStatus status;\n");
    out.push_str("    size_t matched_count;\n");
    out.push_str("    const char* error_message;\n");
    out.push_str("} CorvidFindAgentsResult;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_APPROVAL_ACCEPT = 0,\n");
    out.push_str("    CORVID_APPROVAL_REJECT = 1,\n");
    out.push_str("} CorvidApprovalDecision;\n\n");

    out.push_str("typedef CorvidApprovalDecision (*CorvidApproverFn)(\n");
    out.push_str("    const CorvidApprovalRequired* request,\n");
    out.push_str("    void* user_data);\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_APPROVER_OK = 0,\n");
    out.push_str("    CORVID_APPROVER_IO_ERROR = 1,\n");
    out.push_str("    CORVID_APPROVER_COMPILE_ERROR = 2,\n");
    out.push_str("    CORVID_APPROVER_MISSING_AGENT = 3,\n");
    out.push_str("    CORVID_APPROVER_BAD_SIGNATURE = 4,\n");
    out.push_str("    CORVID_APPROVER_UNSAFE = 5,\n");
    out.push_str("    CORVID_APPROVER_OVER_BUDGET = 6,\n");
    out.push_str("} CorvidApproverLoadStatus;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_PREDICATE_OK = 0,\n");
    out.push_str("    CORVID_PREDICATE_BAD_ARGS = 1,\n");
    out.push_str("    CORVID_PREDICATE_SITE_NOT_FOUND = 2,\n");
    out.push_str("    CORVID_PREDICATE_UNEVALUABLE = 3,\n");
    out.push_str("} CorvidPredicateStatus;\n\n");

    out.push_str("typedef struct {\n");
    out.push_str("    CorvidPredicateStatus status;\n");
    out.push_str("    uint8_t requires_approval;\n");
    out.push_str("    const char* bad_args_message;\n");
    out.push_str("} CorvidPredicateResult;\n\n");

    out.push_str("typedef enum {\n");
    out.push_str("    CORVID_HOST_EVENT_OK = 0,\n");
    out.push_str("    CORVID_HOST_EVENT_BAD_JSON = 1,\n");
    out.push_str("    CORVID_HOST_EVENT_TRACE_DISABLED = 2,\n");
    out.push_str("    CORVID_HOST_EVENT_RUNTIME_ERROR = 3,\n");
    out.push_str("} CorvidHostEventStatus;\n\n");

    out.push_str("#define CORVID_NULL_GROUNDED_HANDLE ((uint64_t)0)\n\n");
    out.push_str("#define CORVID_NULL_OBSERVATION_HANDLE ((uint64_t)0)\n\n");

    out.push_str("const char* corvid_abi_descriptor_json(size_t* out_len);\n");
    out.push_str("void corvid_abi_descriptor_hash(uint8_t out_hash[32]);\n");
    out.push_str("int corvid_abi_verify(const uint8_t expected[32]);\n");
    out.push_str("size_t corvid_list_agents(CorvidAgentHandle* out, size_t capacity);\n");
    out.push_str("CorvidFindAgentsResult corvid_find_agents_where(\n");
    out.push_str("    const char* filter_json,\n");
    out.push_str("    size_t filter_len,\n");
    out.push_str("    size_t* out_indices,\n");
    out.push_str("    size_t out_cap);\n");
    out.push_str("const char* corvid_agent_signature_json(const char* agent_name, size_t* out_len);\n");
    out.push_str("CorvidPreFlight corvid_pre_flight(const char* agent_name, const char* args_json, size_t args_len);\n");
    out.push_str("CorvidCallStatus corvid_call_agent(\n");
    out.push_str("    const char* agent_name,\n");
    out.push_str("    const char* args_json,\n");
    out.push_str("    size_t args_len,\n");
    out.push_str("    char** out_result,\n");
    out.push_str("    size_t* out_result_len,\n");
    out.push_str("    uint64_t* out_observation_handle,\n");
    out.push_str("    CorvidApprovalRequired* out_approval);\n");
    out.push_str("void corvid_free_result(char* result);\n");
    out.push_str("void corvid_register_approver(CorvidApproverFn fn, void* user_data);\n");
    out.push_str("CorvidApproverLoadStatus corvid_register_approver_from_source(\n");
    out.push_str("    const char* source_path,\n");
    out.push_str("    double max_budget_usd_per_call,\n");
    out.push_str("    char** out_error_message);\n");
    out.push_str("void corvid_clear_approver(void);\n");
    out.push_str("bool corvid_mark_preapproved_request(\n");
    out.push_str("    const char* site_name,\n");
    out.push_str("    const char* args_json,\n");
    out.push_str("    size_t args_len);\n");
    out.push_str("const char* corvid_approval_predicate_json(const char* site_name, size_t* out_len);\n");
    out.push_str("CorvidPredicateResult corvid_evaluate_approval_predicate(\n");
    out.push_str("    const char* site_name,\n");
    out.push_str("    const char* args_json,\n");
    out.push_str("    size_t args_len);\n");
    out.push_str("int32_t corvid_grounded_sources(uint64_t handle, const char** out, size_t capacity);\n");
    out.push_str("double corvid_grounded_confidence(uint64_t handle);\n");
    out.push_str("void corvid_grounded_release(uint64_t handle);\n");
    out.push_str("double corvid_observation_cost_usd(uint64_t handle);\n");
    out.push_str("uint64_t corvid_observation_latency_ms(uint64_t handle);\n");
    out.push_str("uint64_t corvid_observation_tokens_in(uint64_t handle);\n");
    out.push_str("uint64_t corvid_observation_tokens_out(uint64_t handle);\n");
    out.push_str("bool corvid_observation_exceeded_bound(uint64_t handle);\n");
    out.push_str("void corvid_observation_release(uint64_t handle);\n");
    out.push_str("CorvidHostEventStatus corvid_record_host_event(\n");
    out.push_str("    const char* name,\n");
    out.push_str("    const char* payload_json,\n");
    out.push_str("    size_t payload_len);\n");
    out.push_str("void corvid_free_string(const char* value);\n\n");

    for agent in agents {
        out.push_str(&format!("// {}\n", agent.signature_comment));
        // Slice 33Q8: per-agent struct boundary schemas (when
        // present) so the C caller knows the JSON shape to send
        // and decode.
        if !agent.json_schema_comments.is_empty() {
            out.push_str(&agent.json_schema_comments);
        }
        out.push_str(&format!(
            "{} {}({});\n\n",
            agent.return_c_type, agent.name, agent.params_c
        ));
    }

    out.push_str("#ifdef __cplusplus\n");
    out.push_str("}\n");
    out.push_str("#endif\n\n");
    out.push_str(&format!("#endif // {guard}\n"));
    out
}

fn include_guard(library_name: &str) -> String {
    let mut guard = String::from("CORVID_");
    for ch in library_name.chars() {
        if ch.is_ascii_alphanumeric() {
            guard.push(ch.to_ascii_uppercase());
        } else {
            guard.push('_');
        }
    }
    guard.push_str("_H");
    guard
}
