use crate::error::WasmCodegenError;
use crate::WasmHostImport;
use corvid_ir::IrAgent;
use corvid_types::Type;
use serde::Serialize;

#[derive(Debug, Clone)]
pub struct WasmArtifacts {
    pub wasm: Vec<u8>,
    pub js_loader: String,
    pub ts_types: String,
    pub manifest_json: String,
}

#[derive(Debug, Serialize)]
struct WasmManifest {
    schema_version: u32,
    module_name: String,
    target: &'static str,
    exports: Vec<WasmExport>,
    imports: Vec<WasmImport>,
    host_capability_abi: &'static str,
    non_scope: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
struct WasmExport {
    name: String,
    params: Vec<WasmParam>,
    return_type: String,
}

#[derive(Debug, Serialize)]
struct WasmParam {
    name: String,
    ty: String,
}

#[derive(Debug, Serialize)]
struct WasmImport {
    kind: &'static str,
    source_name: String,
    import_module: &'static str,
    import_name: String,
    params: Vec<WasmParam>,
    return_type: String,
}

pub(crate) fn build_artifacts(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
    wasm: Vec<u8>,
) -> Result<WasmArtifacts, WasmCodegenError> {
    Ok(WasmArtifacts {
        wasm,
        js_loader: emit_js_loader(module_name, agents, imports)?,
        ts_types: emit_ts_types(agents, imports)?,
        manifest_json: emit_manifest(module_name, agents, imports)?,
    })
}

fn ts_type(ty: &Type) -> Result<&'static str, WasmCodegenError> {
    match ty {
        Type::Int => Ok("bigint"),
        Type::Float => Ok("number"),
        Type::Bool => Ok("boolean"),
        Type::Nothing => Ok("void"),
        // Slice 20n-B-2a: surface a `String` agent param/return as
        // `string` in the generated `.d.ts`. The JS loader still
        // emits the legacy `<agent>(<scalar args>)` glue today —
        // the loader's String-aware packing/unpacking is shipped
        // by commit 3 of this slice. Until then, calling a String
        // agent through the loader will see two raw `i32` arguments
        // instead of a string. The `.d.ts` mapping is deliberately
        // shipped early so the binary-shape regression tests in
        // 2a have something to assert against.
        Type::String => Ok("string"),
        _ => Err(WasmCodegenError::unsupported(format!(
            "unsupported TypeScript wasm surface type `{}`",
            ty.display_name()
        ))),
    }
}

fn js_return_expr(name: &str, ty: &Type) -> String {
    match ty {
        Type::Bool => "Boolean(result)".into(),
        Type::Nothing => "undefined".into(),
        _ => name.into(),
    }
}

fn emit_js_loader(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let mut out = String::new();
    out.push_str("// Auto-generated by Corvid. Do not edit.\n");
    out.push_str(&format!(
        "const WASM_URL = new URL('./{module_name}.wasm', import.meta.url);\n\n"
    ));
    out.push_str("function missing(kind, name) {\n");
    out.push_str("  throw new Error(`Corvid WASM host ${kind} '${name}' is not provided`);\n");
    out.push_str("}\n\n");
    out.push_str("function traceValue(value) {\n");
    out.push_str("  if (typeof value === 'bigint') {\n");
    out.push_str("    const asNumber = Number(value);\n");
    out.push_str("    return Number.isSafeInteger(asNumber) ? asNumber : value.toString();\n");
    out.push_str("  }\n");
    out.push_str("  return value;\n");
    out.push_str("}\n\n");
    out.push_str("function freshRunId() {\n");
    out.push_str("  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID();\n");
    out.push_str("  return `wasm-${Date.now()}-${Math.random().toString(16).slice(2)}`;\n");
    out.push_str("}\n\n");
    out.push_str("function makeTraceContext(trace) {\n");
    out.push_str("  const sink = trace ?? null;\n");
    out.push_str("  return {\n");
    out.push_str("    activeRunId: null,\n");
    out.push_str("    emit(event) {\n");
    out.push_str("      if (!sink) return;\n");
    out.push_str("      if (Array.isArray(sink)) sink.push(event);\n");
    out.push_str("      else if (typeof sink === 'function') sink(event);\n");
    out.push_str("      else if (Array.isArray(sink.events)) sink.events.push(event);\n");
    out.push_str("    },\n");
    out.push_str("    beginRun(agent, args) {\n");
    out.push_str("      const runId = freshRunId();\n");
    out.push_str("      this.activeRunId = runId;\n");
    out.push_str("      this.emit({ kind: 'schema_header', version: 2, writer: 'corvid-codegen-wasm', commit_sha: null, source_path: null, ts_ms: Date.now(), run_id: runId });\n");
    out.push_str("      this.emit({ kind: 'run_started', ts_ms: Date.now(), run_id: runId, agent, args: args.map(traceValue) });\n");
    out.push_str("      return runId;\n");
    out.push_str("    },\n");
    out.push_str("    completeRun(runId, ok, result, error) {\n");
    out.push_str("      this.emit({ kind: 'run_completed', ts_ms: Date.now(), run_id: runId, ok, result: result === undefined ? null : traceValue(result), error: error ?? null });\n");
    out.push_str("      this.activeRunId = null;\n");
    out.push_str("    },\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("function adaptImportsWithContext(host = {}, traceContext) {\n");
    out.push_str("  return {\n");
    out.push_str("    'corvid:host': {\n");
    for import in imports {
        let call_line = format!(
            "(host.{}?.['{}'] ?? (() => missing('{}', '{}')))(...args)",
            import.kind.namespace(),
            import.source_name,
            import.kind.label(),
            import.source_name
        );
        let run_id = "const runId = traceContext.activeRunId ?? freshRunId();\n";
        let args_event = "args: args.map(traceValue)";
        out.push_str(&format!(
            "      '{}': (...args) => {{\n",
            import.import_name
        ));
        out.push_str("        ");
        out.push_str(run_id);
        match import.kind.label() {
            "prompt" => {
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'llm_call', ts_ms: Date.now(), run_id: runId, prompt: '{}', model: null, model_version: null, rendered: null, {} }});\n",
                    import.source_name, args_event
                ));
                out.push_str(&format!("        const result = {};\n", call_line));
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'llm_result', ts_ms: Date.now(), run_id: runId, prompt: '{}', model: null, model_version: null, result: traceValue(result) }});\n",
                    import.source_name
                ));
            }
            "tool" => {
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'tool_call', ts_ms: Date.now(), run_id: runId, tool: '{}', {} }});\n",
                    import.source_name, args_event
                ));
                out.push_str(&format!("        const result = {};\n", call_line));
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'tool_result', ts_ms: Date.now(), run_id: runId, tool: '{}', result: traceValue(result) }});\n",
                    import.source_name
                ));
            }
            "approval" => {
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'approval_request', ts_ms: Date.now(), run_id: runId, label: '{}', {} }});\n",
                    import.source_name, args_event
                ));
                out.push_str(&format!("        const result = Boolean({});\n", call_line));
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'approval_decision', ts_ms: Date.now(), run_id: runId, site: '{}', args: args.map(traceValue), accepted: result, decider: 'wasm-host', rationale: null }});\n",
                    import.source_name
                ));
                out.push_str(&format!(
                    "        traceContext.emit({{ kind: 'approval_response', ts_ms: Date.now(), run_id: runId, label: '{}', approved: result }});\n",
                    import.source_name
                ));
            }
            _ => {}
        }
        out.push_str("        return result;\n");
        out.push_str("      },\n");
    }
    out.push_str("    },\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("export function adaptImports(host = {}, trace = undefined) {\n");
    out.push_str("  return adaptImportsWithContext(host, makeTraceContext(trace));\n");
    out.push_str("}\n\n");
    out.push_str("function indexedDbRequest(request) {\n");
    out.push_str("  return new Promise((resolve, reject) => {\n");
    out.push_str("    request.onsuccess = () => resolve(request.result);\n");
    out.push_str("    request.onerror = () => reject(request.error ?? new Error('IndexedDB request failed'));\n");
    out.push_str("  });\n");
    out.push_str("}\n\n");
    out.push_str("export async function createIndexedDbStoreHost(options = {}) {\n");
    out.push_str("  const dbName = options.dbName ?? 'corvid-wasm-store';\n");
    out.push_str("  const storeName = options.storeName ?? 'records';\n");
    out.push_str("  const db = await new Promise((resolve, reject) => {\n");
    out.push_str("    if (!globalThis.indexedDB) {\n");
    out.push_str("      reject(new Error('IndexedDB is not available'));\n");
    out.push_str("      return;\n");
    out.push_str("    }\n");
    out.push_str("    const request = globalThis.indexedDB.open(dbName, 1);\n");
    out.push_str("    request.onupgradeneeded = () => {\n");
    out.push_str("      if (!request.result.objectStoreNames.contains(storeName)) request.result.createObjectStore(storeName);\n");
    out.push_str("    };\n");
    out.push_str("    request.onsuccess = () => resolve(request.result);\n");
    out.push_str("    request.onerror = () => reject(request.error ?? new Error('open IndexedDB store failed'));\n");
    out.push_str("  });\n");
    out.push_str("  function objectStore(mode) {\n");
    out.push_str("    return db.transaction(storeName, mode).objectStore(storeName);\n");
    out.push_str("  }\n");
    out.push_str("  return {\n");
    out.push_str("    store: {\n");
    out.push_str("      async get(key) {\n");
    out.push_str("        const value = await indexedDbRequest(objectStore('readonly').get(String(key)));\n");
    out.push_str("        return value === undefined ? null : value;\n");
    out.push_str("      },\n");
    out.push_str("      async put(key, value) {\n");
    out.push_str("        await indexedDbRequest(objectStore('readwrite').put(value, String(key)));\n");
    out.push_str("        return value;\n");
    out.push_str("      },\n");
    out.push_str("      async delete(key) {\n");
    out.push_str("        await indexedDbRequest(objectStore('readwrite').delete(String(key)));\n");
    out.push_str("      },\n");
    out.push_str("    },\n");
    out.push_str("    close() {\n");
    out.push_str("      db.close();\n");
    out.push_str("    },\n");
    out.push_str("  };\n");
    out.push_str("}\n\n");
    out.push_str("export async function instantiate(hostOrImports = {}, options = {}) {\n");
    out.push_str("  const traceContext = makeTraceContext(options.trace);\n");
    out.push_str("  const imports = hostOrImports['corvid:host'] ? hostOrImports : adaptImportsWithContext(hostOrImports, traceContext);\n");
    out.push_str("  const source = await WebAssembly.instantiateStreaming(fetch(WASM_URL), imports).catch(async () => {\n");
    out.push_str("    const bytes = await fetch(WASM_URL).then((r) => r.arrayBuffer());\n");
    out.push_str("    return WebAssembly.instantiate(bytes, imports);\n");
    out.push_str("  });\n");
    out.push_str("  const exports = source.instance.exports;\n");
    out.push_str("  return {\n");
    for agent in agents {
        let params = agent
            .params
            .iter()
            .map(|param| param.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {}({}) {{\n", agent.name, params));
        let args_array = if params.is_empty() {
            "[]".to_string()
        } else {
            format!("[{params}]")
        };
        out.push_str(&format!(
            "      const runId = traceContext.beginRun('{}', {});\n",
            agent.name, args_array
        ));
        match agent.return_ty {
            Type::Nothing => {
                out.push_str("      try {\n");
                out.push_str(&format!("        exports.{}({});\n", agent.name, params));
                out.push_str("        traceContext.completeRun(runId, true, undefined, null);\n");
                out.push_str("        return undefined;\n");
                out.push_str("      } catch (error) {\n");
                out.push_str("        traceContext.completeRun(runId, false, undefined, String(error?.message ?? error));\n");
                out.push_str("        throw error;\n");
                out.push_str("      }\n");
            }
            Type::Bool => {
                out.push_str("      try {\n");
                out.push_str(&format!(
                    "        const result = exports.{}({});\n",
                    agent.name, params
                ));
                out.push_str("        const value = Boolean(result);\n");
                out.push_str("        traceContext.completeRun(runId, true, value, null);\n");
                out.push_str(&format!(
                    "        return {};\n",
                    js_return_expr("result", &agent.return_ty)
                ));
                out.push_str("      } catch (error) {\n");
                out.push_str("        traceContext.completeRun(runId, false, undefined, String(error?.message ?? error));\n");
                out.push_str("        throw error;\n");
                out.push_str("      }\n");
            }
            _ => {
                out.push_str("      try {\n");
                out.push_str(&format!(
                    "        const result = exports.{}({});\n",
                    agent.name, params
                ));
                out.push_str("        traceContext.completeRun(runId, true, result, null);\n");
                out.push_str("        return result;\n");
                out.push_str("      } catch (error) {\n");
                out.push_str("        traceContext.completeRun(runId, false, undefined, String(error?.message ?? error));\n");
                out.push_str("        throw error;\n");
                out.push_str("      }\n");
            }
        }
        out.push_str("    },\n");
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_ts_types(
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let mut out = String::new();
    out.push_str("// Auto-generated by Corvid. Do not edit.\n");
    out.push_str("export interface CorvidWasmHost {\n");
    out.push_str("  prompts?: {\n");
    for import in imports.iter().filter(|import| import.kind.namespace() == "prompts") {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("  tools?: {\n");
    for import in imports.iter().filter(|import| import.kind.namespace() == "tools") {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("  approvals?: {\n");
    for import in imports
        .iter()
        .filter(|import| import.kind.namespace() == "approvals")
    {
        out.push_str(&format!("    '{}': {};\n", import.source_name, host_fn_type(import)?));
    }
    out.push_str("  };\n");
    out.push_str("  store?: CorvidWasmStoreHost;\n");
    out.push_str("}\n\n");
    out.push_str("export interface CorvidWasmStoreHost {\n");
    out.push_str("  get(key: string): Promise<unknown | null>;\n");
    out.push_str("  put(key: string, value: unknown): Promise<unknown>;\n");
    out.push_str("  delete(key: string): Promise<void>;\n");
    out.push_str("}\n\n");
    out.push_str("export interface CorvidIndexedDbStoreOptions {\n");
    out.push_str("  dbName?: string;\n");
    out.push_str("  storeName?: string;\n");
    out.push_str("}\n\n");
    out.push_str("export type CorvidIndexedDbStoreHost = CorvidWasmHost & { close(): void };\n\n");
    out.push_str("export interface CorvidWasmModule {\n");
    for agent in agents {
        let params = agent
            .params
            .iter()
            .map(|param| Ok(format!("{}: {}", param.name, ts_type(&param.ty)?)))
            .collect::<Result<Vec<_>, WasmCodegenError>>()?
            .join(", ");
        out.push_str(&format!(
            "  {}({}): {};\n",
            agent.name,
            params,
            ts_type(&agent.return_ty)?
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export type CorvidWasmTraceSink = Array<Record<string, unknown>> | ((event: Record<string, unknown>) => void) | { events: Array<Record<string, unknown>> };\n",
    );
    out.push_str(
        "export interface CorvidWasmInstantiateOptions { trace?: CorvidWasmTraceSink; }\n",
    );
    out.push_str(
        "export function adaptImports(host?: CorvidWasmHost, trace?: CorvidWasmTraceSink): WebAssembly.Imports;\n",
    );
    out.push_str(
        "export function createIndexedDbStoreHost(options?: CorvidIndexedDbStoreOptions): Promise<CorvidIndexedDbStoreHost>;\n",
    );
    out.push_str(
        "export function instantiate(hostOrImports?: WebAssembly.Imports | CorvidWasmHost, options?: CorvidWasmInstantiateOptions): Promise<CorvidWasmModule>;\n",
    );
    Ok(out)
}

fn host_fn_type(import: &WasmHostImport) -> Result<String, WasmCodegenError> {
    let params = import
        .params
        .iter()
        .map(|(name, ty)| Ok(format!("{name}: {}", ts_type(ty)?)))
        .collect::<Result<Vec<_>, WasmCodegenError>>()?
        .join(", ");
    Ok(format!("({params}) => {}", ts_type(&import.return_ty)?))
}

fn emit_manifest(
    module_name: &str,
    agents: &[&IrAgent],
    imports: &[WasmHostImport],
) -> Result<String, WasmCodegenError> {
    let exports = agents
        .iter()
        .map(|agent| {
            let params = agent
                .params
                .iter()
                .map(|param| WasmParam {
                    name: param.name.clone(),
                    ty: param.ty.display_name(),
                })
                .collect();
            WasmExport {
                name: agent.name.clone(),
                params,
                return_type: agent.return_ty.display_name(),
            }
        })
        .collect();
    let imports = imports
        .iter()
        .map(|import| WasmImport {
            kind: import.kind.label(),
            source_name: import.source_name.clone(),
            import_module: "corvid:host",
            import_name: import.import_name.clone(),
            params: import
                .params
                .iter()
                .map(|(name, ty)| WasmParam {
                    name: name.clone(),
                    ty: ty.display_name(),
                })
                .collect(),
            return_type: import.return_ty.display_name(),
        })
        .collect();
    let manifest = WasmManifest {
        schema_version: 1,
        module_name: module_name.to_string(),
        target: "wasm32-unknown-unknown",
        exports,
        imports,
        host_capability_abi: "corvid:host scalar imports v1",
        non_scope: vec![
            "string and struct ABI",
            "provenance handles",
            "streaming host callbacks",
        ],
    };
    serde_json::to_string_pretty(&manifest)
        .map_err(|err| WasmCodegenError::unsupported(format!("serialize wasm manifest: {err}")))
}
