// `@corvid/client` — the generic browser client for a Corvid
// application (slice 51l).
//
// This package is shipped once and reused across every Corvid app. The
// per-app types and the typed `Api` class are generated by
// `corvid contract ts-client`, which imports the transport, event
// protocol, pagination helper, and error type from here. Everything
// cross-cutting — session cookies, SSE parsing, typed errors, cursor
// pagination, auth redirects — lives in this package, not in the
// generated code, so upgrades to the moat behavior happen in one place.

export { CorvidClient, type CorvidClientOptions } from "./transport.js";
export { CorvidError } from "./errors.js";
export {
  type AgentEvent,
  type AgentStream,
  type ApprovalRequest,
} from "./events.js";
export { type Page, paginate } from "./pagination.js";
