//! Connector scaffold generation: `corvid add connector <provider>`.
//!
//! The scaffold is DERIVED FROM THE SHIPPED MANIFEST, not hand
//! curated: each manifest scope becomes an effect declaration whose
//! dimensions reflect the manifest (approval-required scopes produce
//! irreversible `trust: human_required` write effects), and each
//! replay-declared operation becomes a tool declaration bound to the
//! matching effect — quarantine-write operations are `dangerous`, so
//! call sites need `approve`. The generated module compiles as-is;
//! the tool BODIES live host-side (connector tools are dispatched
//! through the host tool registry to `corvid_connector_runtime`),
//! which the generated header states plainly.

use corvid_connector_runtime::{
    ConnectorManifest, ConnectorReplayPolicy, ConnectorScopeApproval,
};

fn sanitize(raw: &str) -> String {
    let mut out = String::new();
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    out.trim_matches('_').to_string()
}

/// Generate `src/connectors/<provider>.cor` from the manifest.
pub(crate) fn generate_connector_module(
    provider: &str,
    manifest: &ConnectorManifest,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# GENERATED by `corvid add connector {provider}` from the shipped\n\
         # `{provider}` connector manifest. The tool declarations below are the\n\
         # TYPED BOUNDARY; their bodies live host-side (the host registers each\n\
         # tool name and routes it to corvid_connector_runtime). Probe operations\n\
         # without a host via `corvid connectors run {provider} <op> --mode=mock`.\n\
         #\n\
         # Setup checklist:\n\
         #   1. Mock mode works immediately (no credentials).\n\
         #   2. Real mode: `corvid connectors oauth {provider}` to mint tokens,\n\
         #      then set CORVID_PROVIDER_LIVE=1 (real calls are opt-in).\n\
         #   3. Approval-required operations below are `dangerous` — call\n\
         #      sites need an `approve` statement, checked at compile time.\n"
    ));

    // Scopes → effects.
    let mut read_effect = None;
    let mut write_effect = None;
    for scope in &manifest.scope {
        // Scope ids conventionally start with "<provider>." — strip
        // it so effect names don't double the prefix.
        let scope_stem = scope
            .id
            .strip_prefix(&format!("{provider}."))
            .unwrap_or(&scope.id);
        // `_effect` suffix keeps effect names clear of the tool
        // names generated below (same stem, one namespace).
        let effect_name = format!("{provider}_{}_effect", sanitize(scope_stem));
        out.push('\n');
        out.push_str(&format!(
            "# scope `{}` (provider scope `{}`; data classes: {})\n",
            scope.id,
            scope.provider_scope,
            if scope.data_classes.is_empty() {
                "none declared".to_string()
            } else {
                scope.data_classes.join(", ")
            }
        ));
        out.push_str(&format!("public effect {effect_name}:\n"));
        match scope.approval {
            ConnectorScopeApproval::Required => {
                out.push_str("    trust: human_required\n    reversible: false\n");
                if write_effect.is_none() {
                    write_effect = Some(effect_name.clone());
                }
            }
            ConnectorScopeApproval::None => {
                out.push_str("    reversible: true\n");
                if read_effect.is_none() {
                    read_effect = Some(effect_name.clone());
                }
            }
        }
        if !scope.data_classes.is_empty() {
            out.push_str("    data: private\n");
        }
    }

    // Replay-declared operations → tool declarations.
    for replay in &manifest.replay {
        let op_stem = replay
            .operation
            .strip_prefix(&format!("{provider}."))
            .unwrap_or(&replay.operation);
        let tool_name = format!("{provider}_{}", sanitize(op_stem));
        let (effect, dangerous) = match replay.policy {
            ConnectorReplayPolicy::QuarantineWrite => (
                write_effect.clone().or_else(|| read_effect.clone()),
                true,
            ),
            ConnectorReplayPolicy::RecordRead | ConnectorReplayPolicy::DeterministicMock => {
                (read_effect.clone().or_else(|| write_effect.clone()), false)
            }
        };
        let Some(effect) = effect else { continue };
        out.push('\n');
        out.push_str(&format!(
            "# operation `{}` — replay policy: {}\n",
            replay.operation,
            match replay.policy {
                ConnectorReplayPolicy::RecordRead => "recorded read",
                ConnectorReplayPolicy::QuarantineWrite => "quarantined write",
                ConnectorReplayPolicy::DeterministicMock => "deterministic mock",
            }
        ));
        out.push_str(&format!(
            "public tool {tool_name}(args_json: String) -> String{} uses {effect}\n",
            if dangerous { " dangerous" } else { "" }
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::connectors_cmd::support::shipped_manifests;

    #[test]
    fn every_shipped_connector_scaffold_compiles() {
        for (provider, manifest) in shipped_manifests().expect("manifests load") {
            let module = generate_connector_module(provider, &manifest);
            let compiled = corvid_driver::compile(&module);
            assert!(
                compiled.ok(),
                "scaffold for `{provider}` must compile: {:?}\n{module}",
                compiled.diagnostics
            );
        }
    }

    #[test]
    fn approval_required_operations_are_dangerous() {
        let (_, gmail) = shipped_manifests()
            .expect("manifests load")
            .into_iter()
            .find(|(name, _)| *name == "gmail")
            .expect("gmail shipped");
        let module = generate_connector_module("gmail", &gmail);
        assert!(
            module.contains("dangerous"),
            "gmail's write path must scaffold as dangerous:\n{module}"
        );
        assert!(
            module.contains("trust: human_required"),
            "approval-required scopes must scaffold human_required:\n{module}"
        );
    }
}
