//! TypeScript client generation from the Application Contract
//! (slice 51l).
//!
//! Two thin generated files are produced per app:
//!
//! - `types.ts` — one `interface` per record type and one discriminated
//!   union per sum/error type, so a frontend gets exhaustive, typed
//!   handling of every value the surface exchanges (including the
//!   `@status`/`@ui` error metadata from slice 51e).
//! - `api.ts` — a typed method per public agent/prompt and per route,
//!   plus the auth helpers derived from the `identity` block. Each
//!   method is a one-liner that delegates to the generic
//!   `@corvid/client` transport — the HTTP/SSE/session/error behavior
//!   lives in that shipped package and is REUSED, never regenerated
//!   per app. That is what keeps the generated code small and the
//!   moat (streaming events, approvals, grounding, pagination) in one
//!   audited place.

use crate::app_contract::{ApplicationContract, ContractType};

/// A generated source file: a repo-relative-ish filename plus its
/// contents. The CLI writes each into the chosen output directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub filename: String,
    pub contents: String,
}

/// Generate the `types.ts` + `api.ts` pair for a contract.
pub fn emit_ts_client(contract: &ApplicationContract) -> Vec<GeneratedFile> {
    vec![
        GeneratedFile {
            filename: "types.ts".to_string(),
            contents: emit_types(contract),
        },
        GeneratedFile {
            filename: "api.ts".to_string(),
            contents: emit_api(contract),
        },
    ]
}

const GENERATED_HEADER: &str = "// Generated by `corvid contract ts-client` — do not edit by hand.\n// Regenerate whenever the Corvid source changes; the transport and\n// behavior live in `@corvid/client` and are reused, not regenerated.\n";

fn emit_types(contract: &ApplicationContract) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    for ty in &contract.types {
        out.push_str(&type_declaration(ty));
        out.push('\n');
    }
    out.push_str(&emit_protocol_types(contract));
    out
}

/// Project every declared provider protocol into TypeScript.
///
/// A long-running operation does not return a value, it returns a
/// *lifecycle*, and a client that models it as a nullable result loses
/// the two facts that matter: which states are terminal, and that one of
/// the terminal states is reached by the provider simply being slow. The
/// emitted state union is discriminated on `terminal`, so a `switch` that
/// forgets the deadline outcome fails to compile rather than falling
/// through at runtime.
///
/// The protocol fingerprint is emitted alongside, so a client can tell
/// whether the backend is still running the protocol these types were
/// generated from.
fn emit_protocol_types(contract: &ApplicationContract) -> String {
    let mut out = String::new();
    for connector in &contract.connectors {
        for operation in &connector.operations {
            let Some(protocol) = &operation.protocol else {
                continue;
            };
            let base = format!(
                "{}{}",
                upper_first(&connector.name),
                upper_camel(&operation.name)
            );

            out.push_str(&format!(
                "/** Statuses `{}.{}` may report. Any other status is refused at the\n \
                 * typed boundary rather than coerced. */\n",
                connector.name, operation.name
            ));
            out.push_str(&format!(
                "export type {base}Status =\n{};\n\n",
                protocol
                    .statuses
                    .iter()
                    .map(|s| format!("  | {}", quote(s)))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));

            out.push_str(&format!(
                "/** States an in-flight `{}.{}` intent can be observed in.\n \
                 * Discriminated on `terminal` so an exhaustive `switch` cannot\n \
                 * silently omit an outcome — including `{}`, which is reached\n \
                 * when the provider is merely slow. */\n",
                connector.name, operation.name, protocol.deadline_target
            ));
            let terminal: std::collections::BTreeSet<&str> =
                protocol.terminal.iter().map(|t| t.as_str()).collect();
            let mut states: Vec<&str> = protocol.states.iter().map(|s| s.name.as_str()).collect();
            for t in &protocol.terminal {
                if !states.contains(&t.as_str()) {
                    states.push(t.as_str());
                }
            }
            out.push_str(&format!(
                "export type {base}State =\n{};\n\n",
                states
                    .iter()
                    .map(|state| format!(
                        "  | {{ state: {}; terminal: {} }}",
                        quote(state),
                        terminal.contains(state)
                    ))
                    .collect::<Vec<_>>()
                    .join("\n")
            ));

            out.push_str(&format!(
                "/** The declared protocol, as the backend compiled it. */\n\
                 export const {base}Protocol = {{\n  \
                 fingerprint: {},\n  \
                 initial: {},\n  \
                 terminal: [{}] as const,\n  \
                 deadlineSeconds: {},\n  \
                 deadlineTarget: {},\n  \
                 pollSeconds: {},\n  \
                 onProtocolChange: {},\n\
                 }} as const;\n\n",
                quote(&protocol.fingerprint),
                quote(&protocol.initial),
                protocol
                    .terminal
                    .iter()
                    .map(|t| quote(t))
                    .collect::<Vec<_>>()
                    .join(", "),
                protocol.deadline_secs,
                quote(&protocol.deadline_target),
                protocol
                    .interval
                    .seconds
                    .map(|s| s.to_string())
                    .unwrap_or_else(|| "null".to_string()),
                quote(&protocol.on_protocol_change),
            ));
        }
    }
    out
}

fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn upper_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// `submit_shipment` -> `SubmitShipment`.
fn upper_camel(name: &str) -> String {
    name.split('_').map(upper_first).collect()
}

fn type_declaration(ty: &ContractType) -> String {
    if !ty.variants.is_empty() {
        return sum_type_declaration(ty);
    }
    let mut out = format!("export interface {} {{\n", ty.name);
    for f in &ty.fields {
        let optional = if f.type_name.starts_with("Option<") { "?" } else { "" };
        // A field with an upload surface is a File/Blob on the wire.
        let ts = if f.upload.is_some() {
            "File".to_string()
        } else {
            ts_type(&f.type_name)
        };
        out.push_str(&format!("  {}{}: {};\n", f.name, optional, ts));
    }
    out.push_str("}\n");
    out
}

/// A sum type projects to a discriminated union tagged by `tag`. Error
/// variants keep their `@status` / `@ui` metadata on a companion
/// const map so a frontend renders a default per branch.
fn sum_type_declaration(ty: &ContractType) -> String {
    let mut out = String::new();
    let arms: Vec<String> = ty
        .variants
        .iter()
        .map(|v| {
            let mut fields = format!("{{ tag: \"{}\"", v.name);
            for f in &v.fields {
                fields.push_str(&format!("; {}: {}", f.name, ts_type(&f.type_name)));
            }
            fields.push_str(" }");
            fields
        })
        .collect();
    out.push_str(&format!("export type {} =\n  | {};\n", ty.name, arms.join("\n  | ")));

    // Presentation/status metadata map, when any variant carries it.
    let has_meta = ty
        .variants
        .iter()
        .any(|v| v.status.is_some() || !v.ui.is_empty());
    if has_meta {
        out.push_str(&format!(
            "\nexport const {}Meta: Record<string, {{ status?: number; ui?: Record<string, unknown> }}> = {{\n",
            ty.name
        ));
        for v in &ty.variants {
            if v.status.is_none() && v.ui.is_empty() {
                continue;
            }
            let status = v
                .status
                .map(|s| format!("status: {s}"))
                .unwrap_or_default();
            let ui = if v.ui.is_empty() {
                String::new()
            } else {
                let ui_json = serde_json::to_string(&v.ui).unwrap_or_else(|_| "{}".to_string());
                format!("ui: {ui_json}")
            };
            let body = [status, ui]
                .into_iter()
                .filter(|s| !s.is_empty())
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("  {}: {{ {} }},\n", v.name, body));
        }
        out.push_str("};\n");
    }
    out
}

fn emit_api(contract: &ApplicationContract) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("import { CorvidClient, type AgentStream, type Page } from \"@corvid/client\";\n");
    // Import every generated type so method signatures resolve.
    if !contract.types.is_empty() {
        let names: Vec<&str> = contract.types.iter().map(|t| t.name.as_str()).collect();
        out.push_str(&format!("import type {{ {} }} from \"./types\";\n", names.join(", ")));
    }
    out.push('\n');
    out.push_str("export class Api {\n");
    out.push_str("  constructor(private readonly client: CorvidClient) {}\n\n");

    for agent in &contract.agents {
        out.push_str(&callable_method(agent, "agent"));
    }
    for prompt in &contract.prompts {
        out.push_str(&callable_method(prompt, "prompt"));
    }

    // Auth helpers from the identity block (slice 51h).
    for identity in &contract.identities {
        for provider in &identity.providers {
            out.push_str(&format!(
                "  loginWith_{p}(): void {{ this.client.login(\"{p}\"); }}\n",
                p = sanitize_ident(&provider.name)
            ));
        }
        out.push_str("  session(): Promise<unknown> { return this.client.session(); }\n");
        out.push_str("  logout(): Promise<void> { return this.client.logout(); }\n");
    }

    out.push_str("}\n");
    out
}

fn callable_method(c: &crate::app_contract::ContractCallable, kind: &str) -> String {
    let params: Vec<String> = c
        .inputs
        .iter()
        .map(|p| format!("{}: {}", sanitize_ident(&p.name), ts_type(&p.type_name)))
        .collect();
    let arg_obj = c
        .inputs
        .iter()
        .map(|p| sanitize_ident(&p.name))
        .collect::<Vec<_>>()
        .join(", ");
    let name = sanitize_ident(&c.name);

    if c.capabilities.streaming {
        // A streaming callable returns a typed event stream the client
        // parses from SSE.
        let inner = generic_inner(&c.output_type).unwrap_or_else(|| "unknown".to_string());
        format!(
            "  {name}({params}): AgentStream<{inner}> {{\n    return this.client.stream(\"{orig}\", {{ {arg_obj} }});\n  }}\n\n",
            params = params.join(", "),
            orig = c.name,
        )
    } else {
        let ret = ts_type(&c.output_type);
        let _ = kind;
        format!(
            "  {name}({params}): Promise<{ret}> {{\n    return this.client.invoke(\"{orig}\", {{ {arg_obj} }});\n  }}\n\n",
            params = params.join(", "),
            orig = c.name,
        )
    }
}

/// Map a contract type name to a TypeScript type. Generic wrappers
/// unwrap to the shape a JSON client actually receives, mirroring the
/// OpenAPI projection.
fn ts_type(name: &str) -> String {
    match name {
        "Int" | "Float" => return "number".to_string(),
        "String" | "TraceId" => return "string".to_string(),
        "Bool" => return "boolean".to_string(),
        "Nothing" => return "null".to_string(),
        _ => {}
    }
    if let Some((head, inner)) = split_generic(name) {
        return match head {
            "List" => format!("{}[]", ts_type(inner)),
            "Option" => format!("{} | null", ts_type(inner)),
            "Stream" | "Tainted" => ts_type(inner),
            "Grounded" => format!(
                "{{ value: {}; sources: Array<{{ kind: string; name: string }}> }}",
                ts_type(inner)
            ),
            "Page" => format!("Page<{}>", ts_type(inner)),
            "Upload" => "File".to_string(),
            "Result" => {
                let (ok, err) = inner.split_once(',').unwrap_or((inner, "string"));
                format!(
                    "{{ ok: {} }} | {{ err: {} }}",
                    ts_type(ok.trim()),
                    ts_type(err.trim())
                )
            }
            "Map" => {
                let (_k, v) = inner.split_once(',').unwrap_or(("string", inner));
                format!("Record<string, {}>", ts_type(v.trim()))
            }
            // An unknown generic head keeps its name (a user type).
            _ => name.to_string(),
        };
    }
    // A bare named type is its generated interface/union.
    name.to_string()
}

fn generic_inner(name: &str) -> Option<String> {
    split_generic(name).map(|(_, inner)| ts_type(inner))
}

fn split_generic(name: &str) -> Option<(&str, &str)> {
    let open = name.find('<')?;
    if !name.ends_with('>') {
        return None;
    }
    Some((&name[..open], &name[open + 1..name.len() - 1]))
}

/// Make an identifier safe for TS (the contract already uses valid
/// identifiers, but a defensive replace keeps generated code from ever
/// producing a syntax error on an odd provider alias).
fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn contract_for(src: &str) -> ApplicationContract {
        use crate::app_contract::{effect_decls_of, emit_application_contract, ContractOptions};
        use corvid_types::effects::EffectRegistry;
        let tokens = corvid_syntax::lex(src).expect("lex");
        let (file, perr) = corvid_syntax::parse_file(&tokens);
        assert!(perr.is_empty(), "parse: {perr:?}");
        let resolved = corvid_resolve::resolve(&file);
        assert!(resolved.errors.is_empty(), "resolve: {:?}", resolved.errors);
        let registry = EffectRegistry::from_decls(&effect_decls_of(&file));
        let checked = corvid_types::typecheck(&file, &resolved);
        assert!(checked.errors.is_empty(), "check: {:?}", checked.errors);
        emit_application_contract(
            &file,
            &resolved,
            &checked,
            &registry,
            &ContractOptions {
                source_path: "app.cor",
                compiler_version: "test",
                generated_at: "now",
            },
        )
    }

    #[test]
    fn record_and_error_types_project_to_interfaces_and_unions() {
        let contract = contract_for(
            "public type Answer:
    text: String
    score: Int

public type RefundError:
    @status(404)
    @ui(message: \"Not found.\")
    | PaymentNotFound
    | ApprovalDenied(reason: String)

public agent classify(q: String) -> Answer:
    return Answer(q, 1)
",
        );
        let files = emit_ts_client(&contract);
        let types = &files.iter().find(|f| f.filename == "types.ts").unwrap().contents;
        assert!(types.contains("export interface Answer {"));
        assert!(types.contains("text: string;"));
        assert!(types.contains("score: number;"));
        // Sum type → discriminated union + metadata map.
        assert!(types.contains("export type RefundError ="));
        assert!(types.contains("{ tag: \"PaymentNotFound\" }"));
        assert!(types.contains("{ tag: \"ApprovalDenied\"; reason: string }"));
        assert!(types.contains("export const RefundErrorMeta"));
        assert!(types.contains("status: 404"));
    }

    #[test]
    fn agents_project_to_typed_methods_delegating_to_the_client() {
        let contract = contract_for(
            "public type Answer:
    text: String

public agent classify(question: String) -> Answer:
    return Answer(question)

public agent chat(message: String) -> Stream<String>:
    return stream_answer(message)

tool stream_answer(m: String) -> Stream<String>
",
        );
        let api = &files_api(&contract);
        // Non-streaming → Promise<Answer> via client.invoke.
        assert!(api.contains("classify(question: string): Promise<Answer>"));
        assert!(api.contains("this.client.invoke(\"classify\", { question })"));
        // Streaming → AgentStream<string> via client.stream.
        assert!(api.contains("chat(message: string): AgentStream<string>"));
        assert!(api.contains("this.client.stream(\"chat\", { message })"));
        // Reuses the shipped transport, never regenerates it.
        assert!(api.contains("import { CorvidClient"));
    }

    #[test]
    fn identity_projects_login_helpers() {
        let contract = contract_for(
            "identity app_users:
    provider google
    provider github
    provisioning:
        first_login: open
        tenant: fixed(\"public\")

public agent hello(n: String) -> String:
    return n
",
        );
        let api = files_api(&contract);
        assert!(api.contains("loginWith_google()"));
        assert!(api.contains("loginWith_github()"));
        assert!(api.contains("session():"));
        assert!(api.contains("logout():"));
    }

    fn files_api(contract: &ApplicationContract) -> String {
        emit_ts_client(contract)
            .into_iter()
            .find(|f| f.filename == "api.ts")
            .unwrap()
            .contents
    }
}

#[cfg(test)]
mod protocol_ts_tests {
    use super::*;

    fn contract_for(src: &str) -> ApplicationContract {
        use crate::app_contract::{effect_decls_of, emit_application_contract, ContractOptions};
        use corvid_types::effects::EffectRegistry;
        let tokens = corvid_syntax::lex(src).expect("lex");
        let (file, perr) = corvid_syntax::parse_file(&tokens);
        assert!(perr.is_empty(), "parse: {perr:?}");
        let resolved = corvid_resolve::resolve(&file);
        assert!(resolved.errors.is_empty(), "resolve: {:?}", resolved.errors);
        let registry = EffectRegistry::from_decls(&effect_decls_of(&file));
        let checked = corvid_types::typecheck(&file, &resolved);
        assert!(checked.errors.is_empty(), "check: {:?}", checked.errors);
        emit_application_contract(
            &file,
            &resolved,
            &checked,
            &registry,
            &ContractOptions {
                source_path: "app.cor",
                compiler_version: "test",
                generated_at: "now",
            },
        )
    }

    const SRC: &str = r#"
effect http_write:
    cost: 1.0

type Job:
    id: String
    status: String

connector shipping:
    base_url: "https://api.example.com"
    auth: bearer(secret("SHIPPING_TOKEN"))
    modes: [real]
    operation submit_shipment(order: String) -> Job dangerous uses http_write:
        POST "/shipments" body order
        async:
            statuses: [queued, processing, completed, failed]
            initial: queued
            terminal: [completed, failed]
            deadline: 600s
            deadline_target: failed
            idempotency: intent via header "Idempotency-Key"
            poll GET "/shipments/{id}"
            every: 30s
            on_protocol_change: refuse
            state queued:
                on queued -> queued
                on processing -> processing
                on completed -> completed
                on failed -> failed
            state processing:
                on queued -> processing
                on processing -> processing
                on completed -> completed
                on failed -> failed

agent main() -> Job uses http_write:
    approve SubmitShipment("order-1")
    return submit_shipment("order-1")
"#;

    /// A long-running operation returns a lifecycle, not a value. The
    /// emitted state union is discriminated on `terminal`, so a client
    /// switch that omits an outcome fails to compile instead of falling
    /// through at runtime.
    #[test]
    fn a_protocol_becomes_a_discriminated_state_union() {
        let types = emit_types(&contract_for(SRC));
        assert!(
            types.contains("export type ShippingSubmitShipmentState ="),
            "the state union must be emitted; got:\n{types}"
        );
        assert!(types.contains(r#"{ state: "processing"; terminal: false }"#));
        assert!(types.contains(r#"{ state: "completed"; terminal: true }"#));
        assert!(
            types.contains(r#"{ state: "failed"; terminal: true }"#),
            "the deadline target must appear as a terminal state"
        );
    }

    /// The status universe is closed: a provider status outside it is
    /// refused at the boundary, so the client type must be a closed union
    /// rather than `string`.
    #[test]
    fn the_status_universe_is_emitted_as_a_closed_union() {
        let types = emit_types(&contract_for(SRC));
        assert!(types.contains("export type ShippingSubmitShipmentStatus ="));
        for status in ["queued", "processing", "completed", "failed"] {
            assert!(
                types.contains(&format!(r#"  | "{status}""#)),
                "status `{status}` must be in the union"
            );
        }
        assert!(
            !types.contains("Status = string"),
            "the status type must never widen to `string`"
        );
    }

    /// The client is generated against a specific protocol graph. Shipping
    /// the fingerprint lets it detect that the backend is now running a
    /// different one.
    #[test]
    fn the_generated_client_carries_the_protocol_fingerprint() {
        let types = emit_types(&contract_for(SRC));
        assert!(types.contains("export const ShippingSubmitShipmentProtocol"));
        assert!(
            types.contains("fingerprint: \"sha256:"),
            "the fingerprint must be emitted so a client can detect drift"
        );
        assert!(types.contains("deadlineTarget: \"failed\""));
        assert!(types.contains("onProtocolChange: \"refuse\""));
    }

    /// No protocols, no protocol types — the generator must not emit
    /// scaffolding for a surface the program does not have.
    #[test]
    fn a_contract_without_protocols_emits_no_protocol_types() {
        let types = emit_types(&contract_for("agent main() -> String:\n    return \"hi\"\n"));
        assert!(!types.contains("Protocol = {"));
        assert!(!types.contains("State ="));
    }
}
