//! Generated `src/lib.rs` template — Phase 20j-A12 commit 2.
//!
//! Emits the crate-level shim binding the libloading-based
//! C-ABI symbols + a thin trait surface for each agent. Pulls
//! `BindingContext` for the source-side metadata (package
//! name, descriptor hash, abi spec).

use crate::{is_generated_user_agent, pascal_case, snake_case, BindingContext};

pub(super) fn render_lib_rs(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("// @generated by corvid bind rust.\n");
    out.push_str(&format!(
        "// descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("// corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "// descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("pub mod common;\n");
    out.push_str("pub mod catalog;\n");
    out.push_str("pub mod types;\n");
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        out.push_str(&format!("pub mod {};\n", snake_case(&agent.name)));
    }
    out.push_str("\n");
    out.push_str(
        "pub use catalog::{AgentInfo, Catalog, CatalogQuery, FindAgentsStatus, Reversibility};\n",
    );
    out.push_str("pub use common::{\n");
    out.push_str("    ApprovalDecision, ApprovalRequest, Approver, CallStatus, Client, CorvidError,\n");
    out.push_str("    CorvidResult, CorvidToolFn, DescriptorDrift, Grounded, GroundedProvenance,\n");
    out.push_str("    Observation, TrustTier, Weak, DESCRIPTOR_HASH_HEX,\n");
    out.push_str("};\n");
    out.push_str("pub use types::*;\n");
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        let module_name = snake_case(&agent.name);
        let api_trait = format!("{}Api", pascal_case(&agent.name));
        out.push_str(&format!(
            "pub use {module_name}::{{{api_trait}, {marker}}};\n",
            marker = pascal_case(&agent.name)
        ));
    }
    out
}
