//! Walk an `IrFile` and emit Python source code.
//!
//! Every agent becomes `async def`. Tools, prompts, types, and imports
//! surface as runtime registrations or dataclass definitions. The
//! generated code imports from the `corvid_runtime` Python package,
//! which is provided separately.

use crate::emitter::Emitter;
use corvid_ast::{BinaryOp, Effect, UnaryOp};
use corvid_ir::{
    IrAgent, IrBlock, IrCallKind, IrExpr, IrExprKind, IrFile, IrImport, IrImportSource, IrLiteral,
    IrParam, IrPrompt, IrStmt, IrTool, IrType,
};

/// Emit the full `IrFile` as a single Python module source string.
pub fn emit(ir: &IrFile) -> String {
    let mut cg = Codegen {
        out: Emitter::new(),
    };
    cg.emit_module(ir);
    cg.out.finish()
}

struct Codegen {
    out: Emitter,
}

impl Codegen {
    fn emit_module(&mut self, ir: &IrFile) {
        self.emit_preamble();
        self.emit_user_imports(&ir.imports);
        if !ir.imports.is_empty() {
            self.out.blank_line();
        }
        self.emit_tool_registry(&ir.tools);
        if !ir.tools.is_empty() {
            self.out.blank_line();
        }
        self.emit_prompt_registry(&ir.prompts);
        if !ir.prompts.is_empty() {
            self.out.blank_line();
        }
        self.emit_types(&ir.types);
        if !ir.types.is_empty() {
            self.out.blank_line();
        }
        self.emit_agents(&ir.agents);
    }

    fn emit_preamble(&mut self) {
        self.out
            .writeln("# auto-generated by corvid — do not edit by hand.");
        self.out.writeln("from __future__ import annotations");
        self.out.writeln("from dataclasses import dataclass");
        self.out.writeln(
            "from corvid_runtime import tool_call, approve_gate, llm_call, register_tools, register_prompts",
        );
        self.out.blank_line();
        self.out.writeln("def __corvid_wrap_i64(value):");
        self.out.indent();
        self.out.writeln("value &= (1 << 64) - 1");
        self.out
            .writeln("return value - (1 << 64) if value >= (1 << 63) else value");
        self.out.dedent();
        self.out.blank_line();
    }

    fn emit_user_imports(&mut self, imports: &[IrImport]) {
        for imp in imports {
            match imp.source {
                IrImportSource::Python => {
                    let alias = imp.alias.clone().unwrap_or_else(|| imp.module.clone());
                    if alias == imp.module {
                        self.out.writeln(&format!("import {}", imp.module));
                    } else {
                        self.out
                            .writeln(&format!("import {} as {}", imp.module, alias));
                    }
                }
                IrImportSource::Corvid
                | IrImportSource::RemoteCorvid
                | IrImportSource::PackageCorvid => {
                    let alias = imp.alias.as_deref().unwrap_or(&imp.module);
                    if let Some(hash) = &imp.content_hash {
                        self.out.writeln(&format!(
                            "# corvid import {} hash:{}:{} as {} (lowered separately)",
                            imp.module, hash.algorithm, hash.hex, alias
                        ));
                    } else {
                        self.out.writeln(&format!(
                            "# corvid import {} as {} (lowered separately)",
                            imp.module, alias
                        ));
                    }
                }
            }
        }
    }

    fn emit_tool_registry(&mut self, tools: &[IrTool]) {
        if tools.is_empty() {
            return;
        }
        self.out.writeln("# --- tools ---");
        self.out.writeln("TOOLS = {");
        self.out.indent();
        for t in tools {
            let effect = match t.effect {
                Effect::Safe => "safe",
                Effect::Dangerous => "dangerous",
            };
            self.out.writeln(&format!(
                "\"{}\": {{\"effect\": \"{}\", \"arity\": {}}},",
                escape_string(&t.name),
                effect,
                t.params.len()
            ));
        }
        self.out.dedent();
        self.out.writeln("}");
        self.out.writeln("register_tools(TOOLS)");
    }

    fn emit_prompt_registry(&mut self, prompts: &[IrPrompt]) {
        if prompts.is_empty() {
            return;
        }
        self.out.writeln("# --- prompts ---");
        self.out.writeln("PROMPTS = {");
        self.out.indent();
        for p in prompts {
            let param_names: Vec<String> = p
                .params
                .iter()
                .map(|x| format!("\"{}\"", escape_string(&x.name)))
                .collect();
            self.out.writeln(&format!(
                "\"{}\": {{\"template\": \"{}\", \"params\": [{}]}},",
                escape_string(&p.name),
                escape_string(&p.template),
                param_names.join(", ")
            ));
        }
        self.out.dedent();
        self.out.writeln("}");
        self.out.writeln("register_prompts(PROMPTS)");
    }

    fn emit_types(&mut self, types: &[IrType]) {
        for t in types {
            self.out.writeln("# --- type ---");
            self.out.writeln("@dataclass");
            self.out.writeln(&format!("class {}:", t.name));
            self.out.indent();
            if t.fields.is_empty() {
                self.out.writeln("pass");
            } else {
                for f in &t.fields {
                    self.out
                        .writeln(&format!("{}: {}", f.name, python_type_hint_of(&f.ty, types)));
                }
            }
            self.out.dedent();
            self.out.blank_line();
        }
    }

    fn emit_agents(&mut self, agents: &[IrAgent]) {
        for a in agents {
            self.emit_agent(a);
            self.out.blank_line();
        }
    }

    fn emit_agent(&mut self, a: &IrAgent) {
        self.out.writeln("# --- agent ---");
        let params = self.format_params(&a.params);
        self.out
            .writeln(&format!("async def {}({}):", a.name, params));
        self.out.indent();
        if a.body.stmts.is_empty() {
            self.out.writeln("pass");
        } else {
            self.emit_block(&a.body);
        }
        self.out.dedent();
    }

    fn format_params(&self, ps: &[IrParam]) -> String {
        ps.iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn emit_block(&mut self, b: &IrBlock) {
        for stmt in &b.stmts {
            self.emit_stmt(stmt);
        }
    }

    fn emit_stmt(&mut self, s: &IrStmt) {
        match s {
            IrStmt::Assign { .. } => {
                self.out.writeln(
                    "raise NotImplementedError(\"place assignment (x.field = v / xs[i] = v / +=) is interpreter-only in 45b\")",
                );
            }
            IrStmt::Let { name, value, .. } => {
                self.out.write(&format!("{} = ", name));
                self.emit_expr(value);
                self.out.newline();
            }
            IrStmt::Return { value, .. } => match value {
                Some(e) => {
                    self.out.write("return ");
                    self.emit_expr(e);
                    self.out.newline();
                }
                None => self.out.writeln("return"),
            },
            IrStmt::Yield { value, .. } => {
                self.out.write("yield ");
                self.emit_expr(value);
                self.out.newline();
            }
            IrStmt::If {
                cond,
                then_block,
                else_block,
                ..
            } => {
                self.out.write("if ");
                self.emit_expr(cond);
                self.out.writeln(":");
                self.out.indent();
                if then_block.stmts.is_empty() {
                    self.out.writeln("pass");
                } else {
                    self.emit_block(then_block);
                }
                self.out.dedent();
                if let Some(eb) = else_block {
                    self.out.writeln("else:");
                    self.out.indent();
                    if eb.stmts.is_empty() {
                        self.out.writeln("pass");
                    } else {
                        self.emit_block(eb);
                    }
                    self.out.dedent();
                }
            }
            IrStmt::For {
                var_name,
                iter,
                body,
                ..
            } => {
                self.out.write(&format!("for {} in ", var_name));
                self.emit_expr(iter);
                self.out.writeln(":");
                self.out.indent();
                if body.stmts.is_empty() {
                    self.out.writeln("pass");
                } else {
                    self.emit_block(body);
                }
                self.out.dedent();
            }
            IrStmt::Approve { label, args, .. } => {
                self.out.write(&format!(
                    "await approve_gate(\"{}\", [",
                    escape_string(label)
                ));
                self.emit_expr_list(args);
                self.out.writeln("])");
            }
            IrStmt::Expr { expr, .. } => {
                self.emit_expr(expr);
                self.out.newline();
            }
            IrStmt::While { cond, body, .. } => {
                self.out.write("while ");
                self.emit_expr(cond);
                self.out.writeln(":");
                self.out.indent();
                if body.stmts.is_empty() {
                    self.out.writeln("pass");
                } else {
                    self.emit_block(body);
                }
                self.out.dedent();
            }
            IrStmt::Parallel { .. } => {
                self.out.writeln(
                    "raise NotImplementedError(\"parallel blocks are interpreter-only in 46e\")",
                );
            }
            IrStmt::Destructure { .. } => {
                self.out.writeln(
                    "raise NotImplementedError(\"destructuring is interpreter-only in 45n\")",
                );
            }
            IrStmt::Break { .. } => self.out.writeln("break"),
            IrStmt::Continue { .. } => self.out.writeln("continue"),
            IrStmt::Pass { .. } => self.out.writeln("pass"),
            // Python transpile ignores ownership ops —
            // CPython handles refcount itself.
            IrStmt::Dup { .. } | IrStmt::Drop { .. } => {}
        }
    }

    fn emit_expr_list(&mut self, exprs: &[IrExpr]) {
        for (i, e) in exprs.iter().enumerate() {
            if i > 0 {
                self.out.write(", ");
            }
            self.emit_expr(e);
        }
    }

    fn emit_expr(&mut self, e: &IrExpr) {
        match &e.kind {
            IrExprKind::Match { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"match is interpreter-only in 45i\"))",
                );
            }
            IrExprKind::Lambda { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"lambdas are interpreter-only in 45j\"))",
                );
            }
            IrExprKind::StructLiteral { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"named struct literals are interpreter-only in 45n\"))",
                );
            }
            IrExprKind::MapLiteral { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"Map<K, V> is interpreter-only in 45g\"))",
                );
            }
            IrExprKind::BuiltinMethod { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"builtin methods are interpreter-only in 45c\"))",
                );
            }
            IrExprKind::Literal(lit) => self.emit_literal(lit),
            IrExprKind::Local { name, .. } => self.out.write(name),
            IrExprKind::Decl { name, .. } => self.out.write(name),
            IrExprKind::Call {
                kind,
                callee_name,
                args,
            } => self.emit_call(kind, callee_name, args),
            IrExprKind::FieldAccess { target, field } => {
                self.emit_expr(target);
                self.out.write(&format!(".{}", field));
            }
            IrExprKind::Index { target, index } => {
                self.emit_expr(target);
                self.out.write("[");
                self.emit_expr(index);
                self.out.write("]");
            }
            IrExprKind::BinOp { op, left, right } => {
                self.out.write("(");
                self.emit_expr(left);
                self.out.write(&format!(" {} ", binary_op_str(*op)));
                self.emit_expr(right);
                self.out.write(")");
            }
            IrExprKind::WrappingBinOp { op, left, right } => {
                self.out.write("__corvid_wrap_i64(");
                self.emit_expr(left);
                self.out.write(&format!(" {} ", binary_op_str(*op)));
                self.emit_expr(right);
                self.out.write(")");
            }
            IrExprKind::UnOp { op, operand } => {
                self.out.write(unary_op_str(*op));
                self.emit_expr(operand);
            }
            IrExprKind::WrappingUnOp { op, operand } => {
                self.out.write("__corvid_wrap_i64(");
                self.out.write(unary_op_str(*op));
                self.emit_expr(operand);
                self.out.write(")");
            }
            IrExprKind::UnwrapGrounded { value } => {
                self.emit_expr(value);
            }
            IrExprKind::List { items } => {
                self.out.write("[");
                self.emit_expr_list(items);
                self.out.write("]");
            }
            IrExprKind::WeakNew { .. } | IrExprKind::WeakUpgrade { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"Weak codegen lands in 17g-py\"))",
                );
            }
            IrExprKind::StreamSplitBy { .. }
            | IrExprKind::StreamMerge { .. }
            | IrExprKind::StreamOrderedBy { .. }
            | IrExprKind::StreamResumeToken { .. }
            | IrExprKind::ResumeStream { .. }
            | IrExprKind::Ask { .. }
            | IrExprKind::Choose { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"human-boundary codegen is interpreter-only\"))",
                );
            }
            // Result/Option construction and `?` / `try-retry`
            // control flow are not implemented in the Python
            // transpile tier yet.
            //
            // Until then this tier emits a marker that's invalid
            // Python on purpose — programs using these features
            // simply don't transpile, with a clear error in the
            // generated source. The interpreter tier handles them
            // fully (Dev B's 18a-18c work).
            IrExprKind::ResultOk { .. } | IrExprKind::ResultErr { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"Result codegen is not implemented for Python yet\"))",
                );
            }
            IrExprKind::OptionSome { .. } | IrExprKind::OptionNone => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"Option codegen is not implemented for Python yet\"))",
                );
            }
            IrExprKind::TryPropagate { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"`?` codegen is not implemented for Python yet\"))",
                );
            }
            IrExprKind::TryRetry { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"`try ... retry` codegen is not implemented for Python yet\"))",
                );
            }
            // `replay` expressions require runtime pattern-dispatch
            // over a recorded trace; the Python transpile tier has
            // no trace-loader or pattern-dispatch primitive, and the
            // interpreter tier (Dev B's 21-inv-E-runtime) is where
            // the feature lands. Emit the same invalid-Python-on-purpose
            // marker as the other untransled IR nodes so this tier
            // refuses cleanly if a user tries to transpile a replay
            // program rather than silently evaluating only the else.
            IrExprKind::Replay { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"`replay` codegen is not implemented for Python yet\"))",
                );
            }
        }
    }

    fn emit_call(&mut self, kind: &IrCallKind, name: &str, args: &[IrExpr]) {
        match kind {
            IrCallKind::EnumConstructor { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"sum-type variants are interpreter-only in 45h\"))",
                );
            }
            IrCallKind::ClosureLocal { .. } => {
                self.out.write(
                    "(_ for _ in ()).throw(NotImplementedError(\"closure calls are interpreter-only in 45j\"))",
                );
            }
            IrCallKind::Tool { .. } => {
                self.out
                    .write(&format!("await tool_call(\"{}\", [", escape_string(name)));
                self.emit_expr_list(args);
                self.out.write("])");
            }
            IrCallKind::Prompt { .. } => {
                self.out
                    .write(&format!("await llm_call(\"{}\", [", escape_string(name)));
                self.emit_expr_list(args);
                self.out.write("])");
            }
            IrCallKind::Agent { .. } => {
                self.out.write(&format!("await {}(", name));
                self.emit_expr_list(args);
                self.out.write(")");
            }
            IrCallKind::Fixture { .. } => {
                self.out.write(&format!(
                    "(_ for _ in ()).throw(NotImplementedError(\"test fixture `{}` is interpreter-only\"))",
                    escape_string(name)
                ));
            }
            IrCallKind::StructConstructor { .. } => {
                // User-declared types are emitted as `@dataclass`es.
                // `TypeName(args)` constructs an instance — exactly the
                // Python dataclass calling convention. No await needed.
                self.out.write(&format!("{}(", name));
                self.emit_expr_list(args);
                self.out.write(")");
            }
            IrCallKind::Unknown => {
                // Imported function or unresolved — emit as plain Python call.
                self.out.write(&format!("{}(", name));
                self.emit_expr_list(args);
                self.out.write(")");
            }
        }
    }

    fn emit_literal(&mut self, lit: &IrLiteral) {
        match lit {
            IrLiteral::Int(n) => self.out.write(&n.to_string()),
            IrLiteral::Float(f) => {
                // Ensure a decimal point so Python reads it as float even for whole values.
                let s = format!("{}", f);
                if s.contains('.') || s.contains('e') || s.contains('E') {
                    self.out.write(&s);
                } else {
                    self.out.write(&format!("{}.0", s));
                }
            }
            IrLiteral::String(s) => self.out.write(&format!("\"{}\"", escape_string(s))),
            IrLiteral::Bool(b) => self.out.write(if *b { "True" } else { "False" }),
            IrLiteral::Nothing => self.out.write("None"),
        }
    }
}

fn binary_op_str(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "+",
        BinaryOp::Sub => "-",
        BinaryOp::Mul => "*",
        BinaryOp::Div => "/",
        BinaryOp::Mod => "%",
        BinaryOp::Eq => "==",
        BinaryOp::NotEq => "!=",
        BinaryOp::Lt => "<",
        BinaryOp::LtEq => "<=",
        BinaryOp::Gt => ">",
        BinaryOp::GtEq => ">=",
        BinaryOp::And => "and",
        BinaryOp::Or => "or",
    }
}

fn unary_op_str(op: UnaryOp) -> &'static str {
    match op {
        UnaryOp::Neg => "-",
        // Elided at IR lowering (numeric identity); kept for match
        // exhaustiveness — "+" is valid Python if it ever arrives.
        UnaryOp::Pos => "+",
        UnaryOp::Not => "not ",
    }
}

/// Map a Corvid `Type` to the Python annotation that should appear in
/// the generated module. The full module already imports
/// `from __future__ import annotations`, so unquoted forward references
/// to dataclasses defined later in the same file are valid.
///
/// `types` is the slice of `IrType` decls in the file, used to resolve
/// `Type::Struct(DefId)` to the dataclass name without requiring the
/// caller to thread a separate symbol table.
fn python_type_hint_of(ty: &corvid_types::Type, types: &[IrType]) -> String {
    use corvid_types::Type as T;
    match ty {
        T::Int => "int".into(),
        T::Float => "float".into(),
        T::String => "str".into(),
        T::Bool => "bool".into(),
        T::Nothing => "None".into(),
        T::Map(k, v) => format!(
            "dict[{}, {}]",
            python_type_hint_of(k, types),
            python_type_hint_of(v, types)
        ),
        T::Struct(def_id) => types
            .iter()
            .find(|decl| decl.id == *def_id)
            .map(|decl| decl.name.clone())
            // If the DefId doesn't resolve to one of the declared
            // dataclasses (shouldn't happen for a well-formed module
            // but handle it without crashing codegen) fall back to
            // `object` so the annotation stays valid Python.
            .unwrap_or_else(|| "object".into()),
        T::ImportedStruct(imported) => imported.name.clone(),
        T::List(inner) => format!("list[{}]", python_type_hint_of(inner, types)),
        T::Option(inner) => format!("{} | None", python_type_hint_of(inner, types)),
        T::Function { .. }
        | T::Stream(_)
        | T::Partial(_)
        | T::ResumeToken(_)
        | T::RouteParams(_)
        | T::Unknown => "object".into(),
        // `Result<T, E>` and `Weak<T, ...>` stay `object` until the
        // Python backend picks a concrete representation (wrapper
        // classes vs `typing.Union[T, E]` vs `T | None`-ish shapes).
        // Promoting these to richer annotations is its own slice and
        // out of 20l-B scope.
        T::Result(_, _) | T::Weak(_, _) => "object".into(),
        T::Grounded(inner) => python_type_hint_of(inner, types),
        T::TraceId => "str".into(),
        // Phase 33S3a — `DbHandle` is interpreter-tier only; the
        // Python backend has no representation for the opaque
        // `Arc<rusqlite::Connection>` the variant holds. Emit
        // `object` so the generated Python stays valid; the
        // executing SQLite surface is documented as
        // interpreter-only until cdylib-style FFI lands. The
        // typechecker's contracts surface that constraint to
        // user code before the backend gets here.
        T::DbHandle => "object".into(),
        // Phase 33R5b-a — JsonValue / JsonBuilder also
        // interpreter-tier only. The Python codegen-py backend
        // can lower them as `object` since the cdylib C-ABI
        // exports already exist (corvid_json_parse etc.) and a
        // follow-up slice will wire the bridging; until then,
        // `object` keeps the generated Python valid.
        T::JsonValue => "object".into(),
        T::JsonBuilder => "object".into(),
    }
}

fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}
