//! Python code generator.
//!
//! v0.1 target. Emits Python 3.11+ with async support.
//! Output goes to `target/py/` under each user project.

pub mod codegen;
pub mod emitter;

pub use codegen::emit;

#[cfg(test)]
mod tests {
    use super::*;
    use corvid_ir::lower;
    use corvid_resolve::resolve;
    use corvid_syntax::{lex, parse_file};
    use corvid_types::typecheck;

    fn src_to_py(src: &str) -> String {
        let tokens = lex(src).expect("lex");
        let (file, perr) = parse_file(&tokens);
        assert!(perr.is_empty(), "parse: {perr:?}");
        let resolved = resolve(&file);
        assert!(resolved.errors.is_empty(), "resolve: {:?}", resolved.errors);
        let checked = typecheck(&file, &resolved);
        assert!(checked.errors.is_empty(), "typecheck: {:?}", checked.errors);
        let ir = lower(&file, &resolved, &checked);
        emit(&ir)
    }

    #[test]
    fn emits_preamble() {
        let py = src_to_py("");
        assert!(py.contains("auto-generated by corvid"));
        assert!(py.contains("from corvid_runtime import"));
    }

    #[test]
    fn emits_async_agent() {
        let src = "\
tool greet(name: String) -> String

agent hello(name: String) -> String:
    return greet(name)
";
        let py = src_to_py(src);
        assert!(py.contains("async def hello(name):"));
        assert!(py.contains("return await tool_call(\"greet\", [name])"));
    }

    #[test]
    fn emits_let_and_field_access() {
        let src = "\
type Ticket:
    order_id: String

tool get_order(id: String) -> Order
type Order:
    id: String

agent handle(t: Ticket) -> Order:
    x = get_order(t.order_id)
    return x
";
        let py = src_to_py(src);
        assert!(py.contains("x = await tool_call(\"get_order\", [t.order_id])"));
        assert!(py.contains("return x"));
    }

    #[test]
    fn emits_if_else() {
        let src = "\
agent check(flag: Bool) -> String:
    if flag:
        return \"yes\"
    else:
        return \"no\"
";
        let py = src_to_py(src);
        assert!(py.contains("if flag:"));
        assert!(py.contains("return \"yes\""));
        assert!(py.contains("else:"));
        assert!(py.contains("return \"no\""));
    }

    #[test]
    fn emits_break_continue_pass() {
        // The typechecker strictly infers the loop variable's
        // type from the iterable's element type, so `if x:` on a
        // String (char) is a Bool mismatch. Use an explicit comparison.
        let src = "\
agent loop_stuff(xs: String) -> String:
    for x in xs:
        if x == \"a\":
            break
        continue
    pass
    return xs
";
        let py = src_to_py(src);
        assert!(py.contains("for x in xs:"));
        assert!(py.contains("break"));
        assert!(py.contains("continue"));
    }

    #[test]
    fn emits_dataclass_for_type() {
        let src = "\
type Ticket:
    order_id: String
    user_id: String

agent noop(t: Ticket) -> String:
    return t.order_id
";
        let py = src_to_py(src);
        assert!(py.contains("@dataclass"));
        assert!(py.contains("class Ticket:"));
        assert!(py.contains("order_id: str"));
        assert!(py.contains("user_id: str"));
    }

    #[test]
    fn emits_approve_before_dangerous_tool() {
        let src = "\
tool send_email(to: String, body: String) -> Nothing dangerous

agent notify(to: String) -> Nothing:
    approve SendEmail(to, to)
    return send_email(to, to)
";
        let py = src_to_py(src);
        // Find the indices of the approve and the send_email call.
        let approve_idx = py
            .find("approve_gate(\"SendEmail\"")
            .expect("missing approve_gate call");
        let send_idx = py
            .find("tool_call(\"send_email\"")
            .expect("missing tool_call for send_email");
        assert!(
            approve_idx < send_idx,
            "approve must come before dangerous tool call"
        );
    }

    #[test]
    fn tool_registry_marks_dangerous() {
        let src = "\
tool get_order(id: String) -> Order
tool issue_refund(id: String, amount: Float) -> Receipt dangerous

type Order:
    id: String
type Receipt:
    id: String

agent nop(id: String, amount: Float) -> Receipt:
    approve IssueRefund(id, amount)
    return issue_refund(id, amount)
";
        let py = src_to_py(src);
        assert!(py.contains("\"get_order\": {\"effect\": \"safe\""));
        assert!(py.contains("\"issue_refund\": {\"effect\": \"dangerous\""));
    }

    #[test]
    fn emits_import_passthrough() {
        let src = r#"import python "anthropic" as ant effects: network"#;
        let py = src_to_py(src);
        assert!(py.contains("import anthropic as ant"));
    }

    #[test]
    fn emits_corvid_import_hash_pin_comment() {
        let digest = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
        let src = format!("import \"./policy\" hash:sha256:{digest} as p\n");
        let py = src_to_py(&src);
        assert!(py.contains(&format!(
            "# corvid import ./policy hash:sha256:{digest} as p"
        )));
    }

    #[test]
    fn emits_float_with_decimal_point() {
        let src = "\
agent nums() -> Float:
    return 3.14
";
        let py = src_to_py(src);
        assert!(py.contains("return 3.14"));
    }

    #[test]
    fn emits_bool_and_nothing_literals() {
        let src = "\
agent flags() -> Bool:
    x = true
    y = false
    z = nothing
    return x
";
        let py = src_to_py(src);
        assert!(py.contains("x = True"));
        assert!(py.contains("y = False"));
        assert!(py.contains("z = None"));
    }

    #[test]
    fn emits_binop_with_parens() {
        let src = "\
agent calc() -> Int:
    return 1 + 2
";
        let py = src_to_py(src);
        // Outer parens on the BinOp ensure correct precedence.
        assert!(py.contains("return (1 + 2)"));
    }

    #[test]
    fn emits_wrapping_integer_arithmetic() {
        let src = "\
@wrapping
agent calc(x: Int) -> Int:
    return x + 9223372036854775807
";
        let py = src_to_py(src);
        assert!(py.contains("def __corvid_wrap_i64(value):"));
        assert!(py.contains("return __corvid_wrap_i64(x + 9223372036854775807)"));
    }

    #[test]
    fn nested_struct_field_emits_class_name_not_object() {
        // 20l-B: before this slice the Python codegen mapped every
        // composite field type to `object`, defeating mypy / pyright /
        // IDE autocomplete on the documented Python target. A nested
        // struct field must carry its dataclass name through to the
        // annotation. `from __future__ import annotations` is in the
        // generated preamble so the forward reference doesn't need to
        // be string-quoted.
        let src = "\
type Inner:
    x: Int

type Outer:
    inner: Inner
    label: String

agent describe(o: Outer) -> String:
    return o.label
";
        let py = src_to_py(src);
        assert!(
            py.contains("inner: Inner"),
            "expected nested struct field to carry its class name; got:\n{py}"
        );
        assert!(
            !py.contains("inner: object"),
            "nested struct field must not collapse to `object`; got:\n{py}"
        );
    }

    #[test]
    fn list_field_emits_typed_list_annotation() {
        // 20l-B: `List<T>` was rendered as `object`. The Python target
        // is `list[T]` with the inner element type recursed through
        // python_type_hint_of so nested element types resolve too.
        let src = "\
type Item:
    sku: String

type Cart:
    items: List<Item>

agent enumerate(c: Cart) -> Int:
    return 0
";
        let py = src_to_py(src);
        assert!(
            py.contains("items: list[Item]"),
            "expected typed list annotation; got:\n{py}"
        );
    }

    #[test]
    fn option_field_emits_union_with_none() {
        // 20l-B: `Option<T>` was rendered as `object`. The Python
        // target is `T | None` (PEP 604, valid under
        // `from __future__ import annotations`).
        let src = "\
type Profile:
    email: String

type User:
    profile: Option<Profile>
    handle: String

agent who(u: User) -> String:
    return u.handle
";
        let py = src_to_py(src);
        assert!(
            py.contains("profile: Profile | None"),
            "expected `Profile | None` for Option<Profile>; got:\n{py}"
        );
    }

    #[test]
    fn emits_full_refund_bot() {
        let src = r#"
import python "anthropic" as anthropic effects: network

type Ticket:
    order_id: String

type Order:
    id: String
    amount: Float

type Decision:
    should_refund: Bool

type Receipt:
    refund_id: String

tool get_order(id: String) -> Order
tool issue_refund(id: String, amount: Float) -> Receipt dangerous

prompt decide_refund(ticket: Ticket, order: Order) -> Decision:
    """Decide whether to refund."""

agent refund_bot(ticket: Ticket) -> Decision:
    order = get_order(ticket.order_id)
    decision = decide_refund(ticket, order)

    if decision.should_refund:
        approve IssueRefund(order.id, order.amount)
        issue_refund(order.id, order.amount)

    return decision
"#;
        let py = src_to_py(src);

        // Expected markers must all appear:
        for expected in &[
            "from corvid_runtime import tool_call, approve_gate, llm_call",
            "import anthropic",
            "\"issue_refund\": {\"effect\": \"dangerous\"",
            "class Ticket:",
            "class Order:",
            "class Decision:",
            "class Receipt:",
            "async def refund_bot(ticket):",
            "order = await tool_call(\"get_order\", [ticket.order_id])",
            "decision = await llm_call(\"decide_refund\", [ticket, order])",
            "if decision.should_refund:",
            "await approve_gate(\"IssueRefund\", [order.id, order.amount])",
            "await tool_call(\"issue_refund\", [order.id, order.amount])",
            "return decision",
        ] {
            assert!(
                py.contains(expected),
                "expected `{expected}` in generated Python but not found.\n---\n{py}\n---"
            );
        }
    }
}
