//! Typed-module generation from MCP tool schemas.
//!
//! `corvid add mcp <name>` discovers a server's tools (`tools/list`)
//! and generates `src/mcp/<name>.cor`: one typed public agent per
//! tool, whose parameters come from the tool's JSON `inputSchema`
//! and whose body builds the arguments with the std/json builder
//! (escaping handled by the runtime, never by string concat) before
//! delegating to the governed `mcp_call`. Calls stay inside the
//! moat: untrusted servers remain approval-gated, every call is
//! traced and replay-substituted.
//!
//! Schema mapping (v1): `string` → String, `integer` → Int,
//! `number` → Float, `boolean` → Bool. A tool whose schema has no
//! object properties — or any property outside that set — falls back
//! to a single `args_json: String` parameter, stated in the
//! generated doc comment rather than silently dropped.

/// One discovered MCP tool.
#[derive(Debug, Clone)]
pub struct McpToolDescriptor {
    pub name: String,
    pub description: String,
    pub input_schema: serde_json::Value,
}

impl McpToolDescriptor {
    /// Parse a `tools/list` result entry.
    pub fn from_listing(entry: &serde_json::Value) -> Option<Self> {
        Some(Self {
            name: entry.get("name")?.as_str()?.to_string(),
            description: entry
                .get("description")
                .and_then(|d| d.as_str())
                .unwrap_or_default()
                .to_string(),
            input_schema: entry
                .get("inputSchema")
                .cloned()
                .unwrap_or(serde_json::Value::Null),
        })
    }
}

/// Corvid keywords that cannot be identifiers; sanitized names that
/// collide get a `_tool` suffix.
const KEYWORDS: &[&str] = &[
    "agent", "tool", "prompt", "effect", "type", "import", "use", "return", "if", "else",
    "for", "while", "match", "approve", "public", "fn", "test", "mock", "server", "retry",
    "backoff", "store", "extend", "model", "schedule", "true", "false", "nothing", "and",
    "or", "not", "in", "uses", "dangerous",
];

fn sanitize_ident(raw: &str) -> String {
    let mut out = String::new();
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    let out = out.trim_matches('_').to_string();
    let out = if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("t_{out}")
    } else {
        out
    };
    if KEYWORDS.contains(&out.as_str()) {
        format!("{out}_tool")
    } else {
        out
    }
}

#[derive(Debug)]
enum ParamKind {
    String,
    Int,
    Float,
    Bool,
}

impl ParamKind {
    fn corvid_type(&self) -> &'static str {
        match self {
            Self::String => "String",
            Self::Int => "Int",
            Self::Float => "Float",
            Self::Bool => "Bool",
        }
    }
    fn setter(&self) -> &'static str {
        match self {
            Self::String => "json_object_set_string",
            Self::Int => "json_object_set_int",
            Self::Float => "json_object_set_float",
            Self::Bool => "json_object_set_bool",
        }
    }
}

/// Typed params extracted from an inputSchema, or None when the
/// schema is outside the v1 mapping (→ args_json fallback).
fn typed_params(schema: &serde_json::Value) -> Option<Vec<(String, String, ParamKind)>> {
    let properties = schema.get("properties")?.as_object()?;
    if properties.is_empty() {
        return Some(Vec::new());
    }
    let mut params = Vec::new();
    for (key, prop) in properties {
        let kind = match prop.get("type").and_then(|t| t.as_str())? {
            "string" => ParamKind::String,
            "integer" => ParamKind::Int,
            "number" => ParamKind::Float,
            "boolean" => ParamKind::Bool,
            _ => return None,
        };
        params.push((key.clone(), sanitize_ident(key), kind));
    }
    Some(params)
}

/// Generate the full module source for a server's discovered tools.
pub fn generate_mcp_module(server_name: &str, tools: &[McpToolDescriptor]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# GENERATED by `corvid add mcp {server_name}` — one typed wrapper per tool\n\
         # discovered on the `{server_name}` MCP server. Regenerate after the server\n\
         # changes with `corvid mcp regen {server_name}`. Calls go through the\n\
         # governed `mcp_call`: untrusted servers stay approval-gated, every call\n\
         # is traced and replay-substituted.\n\n\
         import \"../std/mcp\" use mcp_call\n"
    ));
    let uses_builder = tools
        .iter()
        .any(|t| typed_params(&t.input_schema).is_some_and(|p| !p.is_empty()));
    if uses_builder {
        out.push_str(
            "import \"../std/json\" use json_object_new, json_object_set_string, \
             json_object_set_int, json_object_set_float, json_object_set_bool, \
             json_object_finish\n",
        );
    }
    for tool in tools {
        out.push('\n');
        let agent_name = sanitize_ident(&tool.name);
        if !tool.description.is_empty() {
            for line in tool.description.lines().take(3) {
                out.push_str(&format!("# {line}\n"));
            }
        }
        match typed_params(&tool.input_schema) {
            Some(params) if !params.is_empty() => {
                let signature = params
                    .iter()
                    .map(|(_, ident, kind)| format!("{ident}: {}", kind.corvid_type()))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!(
                    "public agent {agent_name}({signature}) -> Result<String, String>:\n"
                ));
                out.push_str("    args = json_object_new()\n");
                for (key, ident, kind) in &params {
                    out.push_str(&format!(
                        "    args = {}(args, \"{key}\", {ident})\n",
                        kind.setter()
                    ));
                }
                out.push_str(&format!(
                    "    return mcp_call(\"{server_name}\", \"{}\", json_object_finish(args))\n",
                    tool.name
                ));
            }
            Some(_) => {
                out.push_str(&format!(
                    "public agent {agent_name}() -> Result<String, String>:\n    return \
                     mcp_call(\"{server_name}\", \"{}\", \"{{}}\")\n",
                    tool.name
                ));
            }
            None => {
                out.push_str(&format!(
                    "# This tool's inputSchema is outside the typed v1 mapping\n\
                     # (string/integer/number/boolean); pass the arguments as a JSON\n\
                     # object string instead.\n\
                     public agent {agent_name}(args_json: String) -> Result<String, String>:\n    \
                     return mcp_call(\"{server_name}\", \"{}\", args_json)\n",
                    tool.name
                ));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn descriptor(name: &str, schema: serde_json::Value) -> McpToolDescriptor {
        McpToolDescriptor {
            name: name.to_string(),
            description: format!("The {name} tool."),
            input_schema: schema,
        }
    }

    #[test]
    fn generates_typed_wrappers_and_fallbacks() {
        let tools = vec![
            descriptor(
                "search-issues",
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "limit": {"type": "integer"},
                    },
                }),
            ),
            descriptor(
                "complex",
                serde_json::json!({
                    "type": "object",
                    "properties": {"filters": {"type": "array"}},
                }),
            ),
            descriptor("ping", serde_json::json!({"type": "object", "properties": {}})),
        ];
        let module = generate_mcp_module("github", &tools);
        // serde_json object keys iterate alphabetically — the
        // generated signature order is deterministic.
        assert!(
            module.contains(
                "public agent search_issues(limit: Int, query: String) -> Result<String, String>:"
            ),
            "{module}"
        );
        assert!(
            module.contains("json_object_set_string(args, \"query\", query)"),
            "{module}"
        );
        assert!(
            module.contains("mcp_call(\"github\", \"search-issues\", json_object_finish(args))"),
            "{module}"
        );
        assert!(
            module.contains("public agent complex(args_json: String) -> Result<String, String>:"),
            "{module}"
        );
        assert!(
            module.contains("public agent ping() -> Result<String, String>:"),
            "{module}"
        );
    }

    #[test]
    fn generated_module_compiles() {
        let tools = vec![descriptor(
            "search-issues",
            serde_json::json!({
                "type": "object",
                "properties": {"query": {"type": "string"}},
            }),
        )];
        let module = generate_mcp_module("github", &tools);
        let compiled = crate::compile(&module);
        assert!(
            compiled.ok(),
            "generated module must compile: {:?}\n{module}",
            compiled.diagnostics
        );
    }

    #[test]
    fn keyword_and_hyphen_tool_names_sanitize() {
        assert_eq!(sanitize_ident("search-issues"), "search_issues");
        assert_eq!(sanitize_ident("tool"), "tool_tool");
        assert_eq!(sanitize_ident("42things"), "t_42things");
    }
}
