use std::path::PathBuf;

use anyhow::Result;

use crate::{
    effective_return_ownership, grounded_inner_kind,
    is_generated_user_agent, pascal_case, python_ctypes_param_type, python_ctypes_return_type,
    python_public_type, python_string_literal, returns_grounded, snake_case, BindingContext,
    GeneratedFile,
};

pub(crate) fn render(context: &BindingContext) -> Result<Vec<GeneratedFile>> {
    let package_dir = PathBuf::from(&context.package_dir_name);
    let mut files = Vec::new();
    files.push(GeneratedFile {
        relative_path: PathBuf::from("pyproject.toml"),
        contents: render_pyproject(context),
    });
    files.push(GeneratedFile {
        relative_path: PathBuf::from("README.md"),
        contents: render_readme(context),
    });
    files.push(GeneratedFile {
        relative_path: package_dir.join("__init__.py"),
        contents: render_init_py(context),
    });
    files.push(GeneratedFile {
        relative_path: package_dir.join("common.py"),
        contents: render_common_py(context),
    });
    files.push(GeneratedFile {
        relative_path: package_dir.join("types.py"),
        contents: render_types_py(context),
    });
    files.push(GeneratedFile {
        relative_path: package_dir.join("catalog.py"),
        contents: render_catalog_py(),
    });
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        files.push(GeneratedFile {
            relative_path: package_dir.join(format!("{}.py", snake_case(&agent.name))),
            contents: render_agent_module(context, agent)?,
        });
    }
    Ok(files)
}

fn render_pyproject(context: &BindingContext) -> String {
    format!(
        r#"[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.0.1"
description = "Generated Corvid Python bindings for {source}"
requires-python = ">=3.9"
"#,
        name = context.package_name.replace('_', "-"),
        source = context.source_stem,
    )
}

fn render_readme(context: &BindingContext) -> String {
    format!(
        "# Generated Corvid Python bindings\n\nGenerated from `{source}`.\nDescriptor sha256: `{hash}`.\ncorvid-bind version: `{version}`.\nDescriptor generated_at: `{generated_at}`.\n",
        source = context.abi.source_path,
        hash = context.descriptor_hash_hex,
        version = context.bind_version,
        generated_at = context.abi.generated_at
    )
}

fn render_init_py(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("# @generated by corvid bind python.\n");
    out.push_str(&format!(
        "# descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("# corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "# descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("from .common import (\n");
    out.push_str("    ApprovalDecision,\n    ApprovalRequest,\n    Approver,\n    CallError,\n    Client,\n");
    out.push_str("    CorvidError,\n    CorvidToolFn,\n    DescriptorDriftError,\n    Grounded,\n    GroundedProvenance,\n    Observation,\n    TrustTier,\n    Weak,\n");
    out.push_str(")\n");
    out.push_str("from .catalog import AgentInfo, Catalog, CatalogQuery, Reversibility\n");
    out.push_str("from .types import *\n");
    for agent in context
        .abi
        .agents
        .iter()
        .filter(|agent| is_generated_user_agent(agent))
    {
        let module = snake_case(&agent.name);
        let marker = pascal_case(&agent.name);
        out.push_str(&format!("from .{module} import {marker}\n"));
    }
    out
}

fn render_common_py(context: &BindingContext) -> String {
    format!(
        r#"# @generated by corvid bind python.
# descriptor sha256: {hash}
# corvid-bind version: {version}
# descriptor generated_at: {generated_at}
from __future__ import annotations

import ctypes
import enum
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, ClassVar, Generic, Optional, Protocol, TypeVar

DESCRIPTOR_HASH_HEX = "{hash}"

# Host-provided tool callback type. Signature mirrors the
# `corvid-runtime` `CorvidToolFn` C ABI:
#   - `args_json` / `args_len` carry the call args as a UTF-8 JSON
#     array, borrowed for the call duration.
#   - The callback returns a freshly-allocated null-terminated JSON
#     C string the runtime reclaims via the global `free()` after
#     dispatching (a `libc.malloc`-allocated buffer is the
#     simplest match on linux-gnu), or `None`/`0` to signal
#     failure.
#   - `user_data` is the opaque pointer the host supplied at
#     registration (currently always `None`).
CorvidToolFn = ctypes.CFUNCTYPE(
    ctypes.c_void_p,
    ctypes.c_char_p,
    ctypes.c_size_t,
    ctypes.c_void_p,
)


class TrustTier(enum.Enum):
    AUTONOMOUS = "autonomous"
    HUMAN_REQUIRED = "human_required"
    SECURITY_REVIEW = "security_review"


class ApprovalDecision(enum.Enum):
    ACCEPT = 0
    REJECT = 1


@dataclass
class ApprovalRequest:
    site_name: str
    predicate_json: str
    args_json: str
    rationale_prompt: str


class Approver(Protocol):
    def decide(self, request: ApprovalRequest) -> ApprovalDecision: ...


class CorvidError(RuntimeError):
    pass


class DescriptorDriftError(CorvidError):
    def __init__(self, expected: str, actual: str) -> None:
        super().__init__(
            f"binding generated from descriptor sha256:{{expected}} but cdylib ships descriptor sha256:{{actual}}"
        )
        self.expected = expected
        self.actual = actual


class CallError(CorvidError):
    pass


class ApprovalRequiredError(CorvidError):
    def __init__(self, request: ApprovalRequest) -> None:
        super().__init__(f"approval required for `{{request.site_name}}`")
        self.request = request


class ApprovalDeniedError(CorvidError):
    def __init__(self, request: ApprovalRequest) -> None:
        super().__init__(f"approval denied for `{{request.site_name}}`")
        self.request = request


class _RawApprovalRequired(ctypes.Structure):
    _fields_ = [
        ("site_name", ctypes.c_char_p),
        ("predicate_json", ctypes.c_char_p),
        ("args_json", ctypes.c_char_p),
        ("rationale_prompt", ctypes.c_char_p),
    ]


class _RawAgentHandle(ctypes.Structure):
    _fields_ = [
        ("name", ctypes.c_char_p),
        ("symbol", ctypes.c_char_p),
        ("source_file", ctypes.c_char_p),
        ("source_line", ctypes.c_uint32),
        ("trust_tier", ctypes.c_uint8),
        ("cost_bound_usd", ctypes.c_double),
        ("reversible", ctypes.c_uint8),
        ("latency_instant", ctypes.c_uint8),
        ("replayable", ctypes.c_uint8),
        ("deterministic", ctypes.c_uint8),
        ("dangerous", ctypes.c_uint8),
        ("pub_extern_c", ctypes.c_uint8),
        ("requires_approval", ctypes.c_uint8),
        ("grounded_source_count", ctypes.c_uint32),
        ("param_count", ctypes.c_uint32),
    ]


class _RawFindAgentsResult(ctypes.Structure):
    _fields_ = [
        ("status", ctypes.c_uint32),
        ("matched_count", ctypes.c_size_t),
        ("error_message", ctypes.c_char_p),
    ]


T = TypeVar("T")


class Observation:
    def __init__(self, library: ctypes.CDLL, handle: int, release_symbol: str) -> None:
        self._library = library
        self._handle = handle
        self._release_symbol = release_symbol

    @property
    def handle(self) -> int:
        return self._handle

    def cost_usd(self) -> float:
        fn = self._library.corvid_observation_cost_usd
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_double
        return float(fn(self._handle))

    def latency_ms(self) -> int:
        fn = self._library.corvid_observation_latency_ms
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_uint64
        return int(fn(self._handle))

    def tokens_in(self) -> int:
        fn = self._library.corvid_observation_tokens_in
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_uint64
        return int(fn(self._handle))

    def tokens_out(self) -> int:
        fn = self._library.corvid_observation_tokens_out
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_uint64
        return int(fn(self._handle))

    def exceeded_bound(self) -> bool:
        fn = self._library.corvid_observation_exceeded_bound
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_bool
        return bool(fn(self._handle))

    def close(self) -> None:
        if self._handle == 0:
            return
        fn = getattr(self._library, self._release_symbol)
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = None
        fn(self._handle)
        self._handle = 0

    def __enter__(self) -> "Observation":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def __del__(self) -> None:
        self.close()


class Weak(Generic[T]):
    def __init__(self, value: T) -> None:
        self.value = value


class Grounded(Generic[T]):
    def __init__(self, library: ctypes.CDLL, payload: T, handle: int, release_symbol: str) -> None:
        self._library = library
        self._payload = payload
        self._handle = handle
        self._release_symbol = release_symbol

    def payload(self) -> T:
        return self._payload

    def provenance(self) -> "GroundedProvenance[T]":
        return GroundedProvenance(self)

    def confidence(self) -> float:
        fn = self._library.corvid_grounded_confidence
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = ctypes.c_double
        return float(fn(self._handle))

    def sources(self) -> list[str]:
        fn = self._library.corvid_grounded_sources
        fn.argtypes = [ctypes.c_uint64, ctypes.POINTER(ctypes.c_char_p), ctypes.c_size_t]
        fn.restype = ctypes.c_int32
        count = fn(self._handle, None, 0)
        if count < 0:
            raise CorvidError("runtime failed to enumerate grounded sources")
        buffer = (ctypes.c_char_p * count)()
        written = fn(self._handle, buffer, count)
        if written < 0:
            raise CorvidError("runtime failed to read grounded sources")
        return [buffer[index].decode("utf-8") for index in range(written)]

    def close(self) -> None:
        if self._handle == 0:
            return
        fn = getattr(self._library, self._release_symbol)
        fn.argtypes = [ctypes.c_uint64]
        fn.restype = None
        fn(self._handle)
        self._handle = 0

    def __enter__(self) -> "Grounded[T]":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def __del__(self) -> None:
        self.close()


class GroundedProvenance(Generic[T]):
    def __init__(self, grounded: Grounded[T]) -> None:
        self._grounded = grounded

    def confidence(self) -> float:
        return self._grounded.confidence()

    def sources(self) -> list[str]:
        return self._grounded.sources()


def _decode(ptr: ctypes.c_char_p | bytes | None) -> str:
    if ptr is None:
        return ""
    if isinstance(ptr, bytes):
        return ptr.decode("utf-8")
    return ctypes.cast(ptr, ctypes.c_char_p).value.decode("utf-8")


def _bytes_c_string(value: str) -> ctypes.c_char_p:
    return ctypes.c_char_p(value.encode("utf-8"))


class Client:
    def __init__(self, library_path: str | Path) -> None:
        self._library = ctypes.CDLL(str(library_path))
        self._verify_descriptor_hash()

    @property
    def library(self) -> ctypes.CDLL:
        return self._library

    def _verify_descriptor_hash(self) -> None:
        fn = self._library.corvid_abi_descriptor_hash
        fn.argtypes = [ctypes.POINTER(ctypes.c_uint8)]
        fn.restype = None
        buf = (ctypes.c_uint8 * 32)()
        fn(buf)
        actual = bytes(buf).hex()
        if actual != DESCRIPTOR_HASH_HEX:
            raise DescriptorDriftError(DESCRIPTOR_HASH_HEX, actual)

    def catalog(self) -> "Catalog":
        from .catalog import Catalog

        return Catalog(self)

    def register_tool(self, name: str, callback) -> None:
        """Register a host-provided tool callback.

        The cdylib's agent bodies dispatch `tool foo(...)` calls
        through the runtime tool registry — the host MUST register
        a callback for each tool an agent will invoke before
        calling that agent. The proc-macro-emitted Rust tool
        wrappers in the cdylib itself are dead-stripped by the
        linker, so the host always provides its own
        implementation.

        `callback` is a `ctypes.CFUNCTYPE` instance matching
        `CorvidToolFn`. The host MUST keep a strong reference to
        the callback object for as long as the agent might invoke
        the tool — ctypes does not retain CFUNCTYPE wrappers,
        and the cdylib stores the bare function pointer.
        """
        fn = self._library.corvid_register_tool
        fn.argtypes = [ctypes.c_char_p, CorvidToolFn, ctypes.c_void_p]
        fn.restype = None
        fn(name.encode("utf-8"), callback, None)

    def _probe_json_agent(
        self,
        agent_name: str,
        args_json: str,
    ) -> tuple[bool, Any, Observation | None, ApprovalRequest | None]:
        call = self._library.corvid_call_agent
        call.argtypes = [
            ctypes.c_char_p,
            ctypes.c_char_p,
            ctypes.c_size_t,
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.POINTER(ctypes.c_size_t),
            ctypes.POINTER(ctypes.c_uint64),
            ctypes.POINTER(_RawApprovalRequired),
        ]
        call.restype = ctypes.c_uint32

        free_result = self._library.corvid_free_result
        free_result.argtypes = [ctypes.c_void_p]
        free_result.restype = None

        result_ptr = ctypes.c_void_p()
        result_len = ctypes.c_size_t()
        observation_handle = ctypes.c_uint64()
        approval = _RawApprovalRequired()
        encoded_args = args_json.encode("utf-8")
        status = int(
            call(
                agent_name.encode("utf-8"),
                encoded_args,
                len(encoded_args),
                ctypes.byref(result_ptr),
                ctypes.byref(result_len),
                ctypes.byref(observation_handle),
                ctypes.byref(approval),
            )
        )
        result_text = None
        if result_ptr.value:
            result_text = ctypes.string_at(result_ptr.value, result_len.value).decode("utf-8")
            free_result(result_ptr)
        if status == 0:
            observation = Observation(self._library, observation_handle.value, "corvid_observation_release")
            return True, json.loads(result_text if result_text is not None else "null"), observation, None
        if status == 4:
            if observation_handle.value:
                Observation(self._library, observation_handle.value, "corvid_observation_release").close()
            request = ApprovalRequest(
                site_name=_decode(approval.site_name),
                predicate_json=_decode(approval.predicate_json),
                args_json=_decode(approval.args_json),
                rationale_prompt=_decode(approval.rationale_prompt),
            )
            return False, None, None, request
        if observation_handle.value:
            Observation(self._library, observation_handle.value, "corvid_observation_release").close()
        message = result_text or f"runtime call failed with status {{status}}"
        raise CallError(message)

    def _mark_preapproved_request(self, site_name: str, args_json: str) -> None:
        fn = self._library.corvid_mark_preapproved_request
        fn.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_size_t]
        fn.restype = ctypes.c_bool
        encoded_args = args_json.encode("utf-8")
        ok = bool(fn(site_name.encode("utf-8"), encoded_args, len(encoded_args)))
        if not ok:
            raise CorvidError("runtime rejected preapproved approval request")

"#,
        hash = context.descriptor_hash_hex,
        version = context.bind_version,
        generated_at = context.abi.generated_at
    )
}

fn render_types_py(context: &BindingContext) -> String {
    let mut out = String::new();
    out.push_str("# @generated by corvid bind python.\n");
    out.push_str(&format!(
        "# descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("# corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "# descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n\n");
    out.push_str("from .common import Grounded, Weak\n\n");
    for ty in &context.abi.types {
        if ty.kind != "struct" {
            continue;
        }
        out.push_str("@dataclass\n");
        out.push_str(&format!("class {}:\n", pascal_case(&ty.name)));
        if ty.fields.is_empty() {
            out.push_str("    pass\n\n");
            continue;
        }
        for field in &ty.fields {
            out.push_str(&format!(
                "    {}: {}\n",
                snake_case(&field.name),
                python_public_type(&field.r#type)
            ));
        }
        out.push('\n');
    }
    out
}

fn render_catalog_py() -> String {
    r#"# @generated by corvid bind python.
from __future__ import annotations

import ctypes
import json
from dataclasses import dataclass
from enum import Enum

from .common import _RawAgentHandle, _RawFindAgentsResult, _decode, Client, CorvidError, TrustTier


class Reversibility(Enum):
    REVERSIBLE = "reversible"
    IRREVERSIBLE = "irreversible"


@dataclass
class AgentInfo:
    name: str
    symbol: str
    source_file: str
    source_line: int
    trust_tier: TrustTier
    cost_bound_usd: float | None
    reversible: Reversibility | None
    replayable: bool
    deterministic: bool
    dangerous: bool
    pub_extern_c: bool
    requires_approval: bool
    grounded_source_count: int
    param_count: int

    @classmethod
    def from_raw(cls, raw: _RawAgentHandle) -> "AgentInfo":
        tier = {
            1: TrustTier.HUMAN_REQUIRED,
            2: TrustTier.SECURITY_REVIEW,
        }.get(raw.trust_tier, TrustTier.AUTONOMOUS)
        reversible = None
        if raw.reversible == 0:
            reversible = Reversibility.REVERSIBLE
        elif raw.reversible == 1:
            reversible = Reversibility.IRREVERSIBLE
        return cls(
            name=_decode(raw.name),
            symbol=_decode(raw.symbol),
            source_file=_decode(raw.source_file),
            source_line=int(raw.source_line),
            trust_tier=tier,
            cost_bound_usd=float(raw.cost_bound_usd) if raw.cost_bound_usd == raw.cost_bound_usd else None,
            reversible=reversible,
            replayable=bool(raw.replayable),
            deterministic=bool(raw.deterministic),
            dangerous=bool(raw.dangerous),
            pub_extern_c=bool(raw.pub_extern_c),
            requires_approval=bool(raw.requires_approval),
            grounded_source_count=int(raw.grounded_source_count),
            param_count=int(raw.param_count),
        )


class Catalog:
    def __init__(self, client: Client) -> None:
        self._client = client

    def query(self) -> "CatalogQuery":
        return CatalogQuery(self._client)

    def where_trust_tier_le(self, tier: TrustTier) -> "CatalogQuery":
        return self.query().where_trust_tier_le(tier)

    def where_cost_bound_usd_le(self, usd: float) -> "CatalogQuery":
        return self.query().where_cost_bound_usd_le(usd)

    def not_dangerous(self) -> "CatalogQuery":
        return self.query().not_dangerous()


class CatalogQuery:
    def __init__(self, client: Client) -> None:
        self._client = client
        self._clauses: list[dict[str, object]] = []

    def where_trust_tier_le(self, tier: TrustTier) -> "CatalogQuery":
        self._clauses.append({"dim": "trust_tier", "op": "le", "value": tier.value})
        return self

    def where_cost_bound_usd_le(self, usd: float) -> "CatalogQuery":
        self._clauses.append({"dim": "cost_bound_usd", "op": "le", "value": usd})
        return self

    def where_latency_p99_ms_le(self, ms: float) -> "CatalogQuery":
        self._clauses.append({"dim": "latency_p99_ms", "op": "le", "value": ms})
        return self

    def not_dangerous(self) -> "CatalogQuery":
        self._clauses.append({"dim": "dangerous", "op": "eq", "value": False})
        return self

    def replayable(self) -> "CatalogQuery":
        self._clauses.append({"dim": "replayable", "op": "eq", "value": True})
        return self

    def deterministic(self) -> "CatalogQuery":
        self._clauses.append({"dim": "deterministic", "op": "eq", "value": True})
        return self

    def find(self) -> list[AgentInfo]:
        find = self._client.library.corvid_find_agents_where
        find.argtypes = [ctypes.c_char_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t), ctypes.c_size_t]
        find.restype = _RawFindAgentsResult
        list_agents = self._client.library.corvid_list_agents
        list_agents.argtypes = [ctypes.POINTER(_RawAgentHandle), ctypes.c_size_t]
        list_agents.restype = ctypes.c_size_t

        if not self._clauses:
            filter_json = json.dumps({"all": [{"dim": "dangerous", "op": "eq", "value": True}, {"not": {"dim": "dangerous", "op": "eq", "value": True}}]})
        elif len(self._clauses) == 1:
            filter_json = json.dumps(self._clauses[0])
        else:
            filter_json = json.dumps({"all": self._clauses})

        raw = find(filter_json.encode("utf-8"), len(filter_json.encode("utf-8")), None, 0)
        if raw.status != 0:
            raise CorvidError(_decode(raw.error_message))
        indices = (ctypes.c_size_t * raw.matched_count)()
        raw = find(filter_json.encode("utf-8"), len(filter_json.encode("utf-8")), indices, raw.matched_count)
        if raw.status != 0:
            raise CorvidError(_decode(raw.error_message))
        total = int(list_agents(None, 0))
        handles = (_RawAgentHandle * total)()
        list_agents(handles, total)
        return [AgentInfo.from_raw(handles[indices[i]]) for i in range(raw.matched_count)]
"#
    .to_string()
}

fn render_agent_module(
    context: &BindingContext,
    agent: &corvid_abi::AbiAgent,
) -> Result<String> {
    let marker = pascal_case(&agent.name);
    let method_name = snake_case(&agent.name);
    let return_type = if returns_grounded(&agent.return_type) {
        format!(
            "Grounded[{}]",
            python_public_type(grounded_inner(agent.return_type()).unwrap())
        )
    } else {
        python_public_type(&agent.return_type)
    };
    let mut out = String::new();
    out.push_str("# @generated by corvid bind python.\n");
    out.push_str(&format!(
        "# descriptor sha256: {}\n",
        context.descriptor_hash_hex
    ));
    out.push_str(&format!("# corvid-bind version: {}\n", context.bind_version));
    out.push_str(&format!(
        "# descriptor generated_at: {}\n",
        context.abi.generated_at
    ));
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import ctypes\n");
    out.push_str("import json\n");
    out.push_str("from typing import ClassVar, Protocol\n\n");
    out.push_str("from .common import (\n");
    out.push_str("    ApprovalDecision,\n    ApprovalDeniedError,\n    Approver,\n    CallError,\n    Client,\n");
    out.push_str("    CorvidError,\n    Grounded,\n    Observation,\n    TrustTier,\n    _decode,\n");
    out.push_str(")\n");
    out.push_str("from .types import *\n\n");
    out.push_str(&format!("class {marker}:\n"));
    out.push_str(&format!(
        "    NAME: ClassVar[str] = {}\n",
        python_string_literal(&agent.name)
    ));
    out.push_str(&format!(
        "    SYMBOL: ClassVar[str] = {}\n",
        python_string_literal(&agent.symbol)
    ));
    out.push_str(&format!(
        "    TRUST_TIER: ClassVar[TrustTier] = TrustTier.{}\n",
        match agent.effects.trust_tier.as_deref() {
            Some("human_required") => "HUMAN_REQUIRED",
            Some("security_review") => "SECURITY_REVIEW",
            _ => "AUTONOMOUS",
        }
    ));
    if let Some(budget) = &agent.budget {
        out.push_str(&format!(
            "    COST_BOUND_USD: ClassVar[float | None] = {}\n",
            budget.usd_per_call
        ));
    } else {
        out.push_str("    COST_BOUND_USD: ClassVar[float | None] = None\n");
    }
    out.push_str(&format!(
        "    IS_DANGEROUS: ClassVar[bool] = {}\n\n",
        if agent.attributes.dangerous { "True" } else { "False" }
    ));

    out.push_str(&format!("class {marker}Api(Protocol):\n"));
    out.push_str(&format!(
        "    def {method_name}(self{sig}) -> tuple[{return_type}, Observation]: ...\n\n",
        sig = render_python_signature_params(agent)
    ));
    out.push_str(&format!("def _{method_name}(client: Client{sig}) -> tuple[{return_type}, Observation]:\n",
        sig = render_python_impl_params(agent)
    ));
    if agent.attributes.dangerous {
        out.push_str(&render_python_dangerous_body(agent)?);
    } else {
        out.push_str(&render_python_direct_body(agent)?);
    }
    out.push('\n');
    out.push_str(&format!("setattr(Client, {name}, _{method_name})\n", name = python_string_literal(&method_name)));
    Ok(out)
}

trait AbiAgentExt {
    fn return_type(&self) -> &corvid_abi::TypeDescription;
}

impl AbiAgentExt for corvid_abi::AbiAgent {
    fn return_type(&self) -> &corvid_abi::TypeDescription {
        &self.return_type
    }
}

fn grounded_inner(ty: &corvid_abi::TypeDescription) -> Option<&corvid_abi::TypeDescription> {
    match ty {
        corvid_abi::TypeDescription::Grounded { grounded } => Some(grounded.inner.as_ref()),
        _ => None,
    }
}

fn render_python_signature_params(agent: &corvid_abi::AbiAgent) -> String {
    let mut out = String::new();
    for param in &agent.params {
        out.push_str(", ");
        out.push_str(&snake_case(&param.name));
        out.push_str(": ");
        out.push_str(&python_public_type(&param.ty));
    }
    if agent.attributes.dangerous {
        out.push_str(", *, approver: Approver");
    }
    out
}

fn render_python_impl_params(agent: &corvid_abi::AbiAgent) -> String {
    let mut out = String::new();
    for param in &agent.params {
        out.push_str(", ");
        out.push_str(&snake_case(&param.name));
        out.push_str(": ");
        out.push_str(&python_public_type(&param.ty));
    }
    if agent.attributes.dangerous {
        out.push_str(", approver: Approver");
    }
    out
}

fn render_python_dangerous_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    let mut out = String::new();
    out.push_str("    args_json = json.dumps([\n");
    for param in &agent.params {
        out.push_str(&format!("        {},\n", snake_case(&param.name)));
    }
    out.push_str("    ])\n");
    out.push_str(&format!(
        "    completed, payload, observation, request = client._probe_json_agent({}, args_json)\n",
        python_string_literal(&agent.name)
    ));
    out.push_str("    if completed:\n");
    out.push_str("        return payload, observation\n");
    out.push_str("    assert request is not None\n");
    out.push_str("    decision = approver.decide(request)\n");
    out.push_str("    if decision == ApprovalDecision.REJECT:\n");
    out.push_str("        raise ApprovalDeniedError(request)\n");
    out.push_str("    client._mark_preapproved_request(request.site_name, request.args_json)\n");
    out.push_str(&render_python_direct_invoke_body(agent, "    ")?);
    Ok(out)
}

fn render_python_direct_body(agent: &corvid_abi::AbiAgent) -> Result<String> {
    render_python_direct_invoke_body(agent, "    ")
}

fn render_python_direct_invoke_body(
    agent: &corvid_abi::AbiAgent,
    indent: &str,
) -> Result<String> {
    let mut out = String::new();
    let return_ownership = effective_return_ownership(agent);
    let return_destructor = return_ownership
        .destructor
        .as_ref()
        .map(|destructor| destructor.symbol.as_str())
        .unwrap_or("corvid_free_string");
    out.push_str(&format!(
        "{indent}fn = client.library.{}\n",
        agent.symbol
    ));
    out.push_str(&format!("{indent}fn.argtypes = [\n"));
    for param in &agent.params {
        out.push_str(&format!(
            "{indent}    {},\n",
            python_ctypes_param_type(&param.ty)?
        ));
    }
    if returns_grounded(&agent.return_type) {
        out.push_str(&format!("{indent}    ctypes.POINTER(ctypes.c_uint64),\n"));
    }
    out.push_str(&format!("{indent}    ctypes.POINTER(ctypes.c_uint64),\n"));
    out.push_str(&format!("{indent}]\n"));
    out.push_str(&format!(
        "{indent}fn.restype = {}\n",
        if returns_grounded(&agent.return_type) {
            python_ctypes_return_type(grounded_inner(agent.return_type()).unwrap())?
        } else {
            python_ctypes_return_type(&agent.return_type)?
        }
    ));
    for (index, param) in agent.params.iter().enumerate() {
        if matches!(
            crate::ffi_scalar_kind(&param.ty),
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId)
        ) {
            out.push_str(&format!(
                "{indent}arg_{index} = {}.encode('utf-8')\n",
                snake_case(&param.name)
            ));
        }
    }
    if returns_grounded(&agent.return_type) {
        out.push_str(&format!("{indent}grounded_handle = ctypes.c_uint64()\n"));
    }
    out.push_str(&format!("{indent}observation_handle = ctypes.c_uint64()\n"));
    let mut call_args = Vec::new();
    for (index, param) in agent.params.iter().enumerate() {
        if matches!(
            crate::ffi_scalar_kind(&param.ty),
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId)
        ) {
            call_args.push(format!("arg_{index}"));
        } else {
            call_args.push(snake_case(&param.name));
        }
    }
    if returns_grounded(&agent.return_type) {
        call_args.push("ctypes.byref(grounded_handle)".to_string());
    }
    call_args.push("ctypes.byref(observation_handle)".to_string());
    out.push_str(&format!("{indent}value = fn({})\n", call_args.join(", ")));
    if returns_grounded(&agent.return_type) {
        match grounded_inner_kind(&agent.return_type).unwrap() {
            corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId => {
                out.push_str(&format!("{indent}free = client.library.corvid_free_string\n"));
                out.push_str(&format!("{indent}free.argtypes = [ctypes.c_void_p]\n"));
                out.push_str(&format!("{indent}free.restype = None\n"));
                out.push_str(&format!("{indent}payload = ctypes.string_at(value).decode('utf-8')\n"));
                out.push_str(&format!("{indent}free(value)\n"));
            }
            _ => out.push_str(&format!("{indent}payload = value\n")),
        }
        out.push_str(&format!(
            "{indent}return Grounded(client.library, payload, grounded_handle.value, {:?}), Observation(client.library, observation_handle.value, 'corvid_observation_release')\n",
            return_destructor
        ));
    } else {
        match crate::ffi_scalar_kind(&agent.return_type) {
            Some(corvid_abi::ScalarTypeName::String | corvid_abi::ScalarTypeName::TraceId) => {
                out.push_str(&format!("{indent}free = client.library.{return_destructor}\n"));
                out.push_str(&format!("{indent}free.argtypes = [ctypes.c_void_p]\n"));
                out.push_str(&format!("{indent}free.restype = None\n"));
                out.push_str(&format!("{indent}payload = ctypes.string_at(value).decode('utf-8')\n"));
                out.push_str(&format!("{indent}free(value)\n"));
                out.push_str(&format!(
                    "{indent}return payload, Observation(client.library, observation_handle.value, 'corvid_observation_release')\n",
                ));
            }
            Some(corvid_abi::ScalarTypeName::Nothing) => {
                out.push_str(&format!(
                    "{indent}return None, Observation(client.library, observation_handle.value, 'corvid_observation_release')\n",
                ));
            }
            _ => {
                out.push_str(&format!(
                    "{indent}return value, Observation(client.library, observation_handle.value, 'corvid_observation_release')\n",
                ));
            }
        }
    }
    Ok(out)
}
